// GENERATED by ayjnt — do not edit.
// Typed useVoiceAgent hook for ChatVoice at /chat.
//
// ChatVoice is built with the `withVoice(...)` mixin from
// `@cloudflare/voice`, so we route React calls through ayjnt's
// custom voice transport (URL: /<route>/<instance>) rather than the
// SDK's default `/agents/<kebab>/<name>` path.
import { AyjntVoiceTransport, useAyjntVoiceAgent } from "ayjnt/voice/client";

/** The agent class, re-exported so callers can `import type { ChatVoice } from "@ayjnt/...".` */
export type { default as ChatVoice } from "../../../agents/chat/agent.ts";

// Re-exported as a value so callers writing framework-agnostic code
// (no React) can construct their own transport against ayjnt's URL
// shape.
export { AyjntVoiceTransport };

/**
 * React hook bound to ChatVoice. Connects over WebSocket to the
 * voice agent at /chat and drives the
 * `@cloudflare/voice` STT/TTS pipeline.
 *
 *   const v = useVoiceAgent();                         // URL-derived instance
 *   const v = useVoiceAgent({ name: "room-42" });      // explicit instance
 *
 * Returns the same shape `useVoiceAgent` from
 * `@cloudflare/voice/react` does: `status`, `transcript`,
 * `interimTranscript`, `audioLevel`, `isMuted`, `startCall`,
 * `endCall`, `toggleMute`, `sendText`, `sendJSON`, etc.
 *
 * We derive the option type from `Parameters<typeof useAyjntVoiceAgent>`
 * rather than re-exporting an upstream type — bunup's d.ts bundling
 * leaves relative imports unresolved in the dist artifact, so the
 * indirect route gives a cleaner consumer-side type resolution.
 */
export function useVoiceAgent(
  options?: Omit<
    Parameters<typeof useAyjntVoiceAgent>[0],
    "agent" | "routePath"
  >,
) {
  return useAyjntVoiceAgent({
    agent: "ChatVoice",
    routePath: "/chat",
    ...(options ?? {}),
  });
}
