// GENERATED by ayjnt — do not edit.
// Typed useAgent hook for ReportsAgent at /admin/reports.
import {
  useAgent as useAgentUpstream,
  type UseAgentOptions,
} from "agents/react";
import type ReportsAgent from "../../../../agents/admin/reports/agent.ts";

/** The agent class, re-exported so callers can `import type { ReportsAgent } from "@ayjnt/...".` */
export type { default as ReportsAgent } from "../../../../agents/admin/reports/agent.ts";

type Instance = InstanceType<typeof ReportsAgent>;
type AgentState = Instance extends { state: infer S } ? S : unknown;

/**
 * React hook bound to ReportsAgent. Derives `basePath` from the agent's
 * route prefix "/admin/reports" and an instance name taken from the current
 * URL. Pass `name` to override the instance:
 *
 *   const agent = useAgent();                       // URL-derived
 *   const agent = useAgent({ name: "room-42" });    // explicit instance
 *
 * The return type carries through to `agent.stub.<method>(...)` and
 * `agent.call("<method>", [...])` — every method on ReportsAgent
 * decorated with `@callable()` from "agents" is reachable with full
 * argument and return-type checking.
 *
 * The hook is bound to ReportsAgent's own state shape — there's no
 * State generic. Renaming a field on the agent's State propagates here
 * automatically on the next `ayjnt build`. If you genuinely need a
 * different shape on the client side, narrow at the use site instead
 * of overriding the type.
 */
export function useAgent(
  options?: Omit<UseAgentOptions<AgentState>, "agent" | "basePath"> & {
    /** Override the URL-derived instance name. */
    name?: string;
  },
): ReturnType<typeof useAgentUpstream<Instance, AgentState>> {
  const { name: overrideName, ...rest } = options ?? {};
  const instanceName = overrideName ?? deriveInstance();
  return useAgentUpstream<Instance, AgentState>({
    agent: "ReportsAgent",
    basePath: "admin/reports" + "/" + instanceName,
    ...rest,
  });
}

/**
 * Pull the instance name out of window.location.pathname.
 *
 *   /admin/reports                        → "default"
 *   /admin/reports/room-42                → "room-42"
 *   /admin/reports/room-42/anything-else  → "room-42"
 */
function deriveInstance(): string {
  if (typeof window === "undefined") return "default";
  const prefix = "/admin/reports";
  const p = window.location.pathname;
  if (p !== prefix && !p.startsWith(prefix + "/")) return "default";
  const remainder = p.slice(prefix.length);
  const parts = remainder.split("/").filter(Boolean);
  return parts[0] ?? "default";
}
