import { DocPageShell } from "@/components/DocPageShell";
import { Callout } from "@/components/Callout";
import { CodeBlock } from "@/components/CodeBlock";

export const metadata = {
	title: "Your first agent — ayjnt docs",
	description:
		"A hands-on walkthrough: create a counter agent, run it locally, and extend it with a method.",
};

export default function Page() {
	return (
		<DocPageShell
			slug="getting-started/your-first-agent"
			lede="Build a working agent end-to-end. The example is a counter: one number, two endpoints, one method. In ten minutes you'll have run, inspected, mutated, and understood every piece."
		>
			<h2>Create the project</h2>
			<CodeBlock
				lang="sh"
				code={`bunx ayjnt new counter-demo
cd counter-demo
bun install`}
			/>
			<p>
				You&apos;ll see a <code>counter-demo/agents/chat/agent.ts</code>{" "}
				that the minimal template created. Delete <code>chat/</code> — we&apos;re
				going to write our own:
			</p>
			<CodeBlock
				lang="sh"
				code={`rm -rf agents/chat
mkdir -p agents/counter`}
			/>

			<h2>Write the agent</h2>
			<p>
				Create <code>agents/counter/agent.ts</code> with this content:
			</p>
			<CodeBlock
				filename="agents/counter/agent.ts"
				lang="ts"
				code={`import { Agent } from "agents";
import type { GeneratedEnv } from "@ayjnt/env";

type State = { count: number };

export default class CounterAgent extends Agent<GeneratedEnv, State> {
  override initialState: State = { count: 0 };

  override async onRequest(request: Request): Promise<Response> {
    if (request.method === "POST") {
      const { by } = (await request.json()) as { by?: number };
      const next = this.state.count + (by ?? 1);
      this.setState({ count: next });
      return Response.json({ count: next, instance: this.name });
    }
    return Response.json({ count: this.state.count, instance: this.name });
  }
}`}
				highlightLines={[1, 2, 4, 6, 7, 11, 12]}
			/>

			<p>Four things are worth naming:</p>
			<ol>
				<li>
					<strong>
						<code>extends Agent&lt;GeneratedEnv, State&gt;</code>
					</strong>{" "}
					— the first type parameter is the worker&apos;s env (DO bindings +
					any KV/R2/vars you declare). <code>GeneratedEnv</code> is
					regenerated by ayjnt on every build and contains exactly the DO
					bindings for every agent in your tree. The second is your state
					shape.
				</li>
				<li>
					<strong>
						<code>override initialState</code>
					</strong>{" "}
					— the value <code>this.state</code> starts at when a new DO
					instance boots for the first time. Required because the base class
					declares an <code>initialState</code> field.
				</li>
				<li>
					<strong>
						<code>override async onRequest</code>
					</strong>{" "}
					— the HTTP entrypoint. Return a <code>Response</code>. Called per
					request; the DO is the same instance across calls.
				</li>
				<li>
					<strong><code>this.setState</code></strong> — persists new state
					and broadcasts it to any connected WebSocket clients. Don&apos;t
					mutate <code>this.state</code> directly — it&apos;s the durable
					shape and ayjnt/Cloudflare both key behavior off{" "}
					<code>setState</code> being the only writer.
				</li>
			</ol>

			<h2>Run it</h2>
			<CodeBlock
				lang="sh"
				code={`bun run dev
# ✓ ayjnt: 1 agent(s) → .ayjnt/dist/wrangler.jsonc
# ⎔ Listening on http://localhost:8787`}
			/>
			<p>
				In another terminal:
			</p>
			<CodeBlock
				lang="sh"
				code={`# Read — no POST body, count starts at 0
curl http://localhost:8787/counter/demo
# → {"count":0,"instance":"demo"}

# Increment by 1
curl -X POST http://localhost:8787/counter/demo \\
  -H "content-type: application/json" -d '{}'
# → {"count":1,"instance":"demo"}

# Increment by 7
curl -X POST http://localhost:8787/counter/demo \\
  -d '{"by":7}' -H "content-type: application/json"
# → {"count":8,"instance":"demo"}

# Different instance — isolated state
curl http://localhost:8787/counter/another
# → {"count":0,"instance":"another"}`}
			/>
			<Callout kind="tip" title="What the URL means">
				<code>/counter/demo</code> — the first segment <code>counter</code>{" "}
				matches the folder path; the second segment <code>demo</code> is
				the DO instance id. Every unique second segment gets its own
				Durable Object with isolated state and storage.
			</Callout>

			<h2>Add a method callable from another agent</h2>
			<p>
				The real power of agents shows up when they call each other. Add a{" "}
				<code>reset</code> method to the class:
			</p>
			<CodeBlock
				filename="agents/counter/agent.ts"
				lang="ts"
				code={`export default class CounterAgent extends Agent<GeneratedEnv, State> {
  override initialState: State = { count: 0 };

  /** Public method — callable across the DO boundary via getAgent<T>. */
  async reset(): Promise<void> {
    this.setState({ count: 0 });
  }

  override async onRequest(request: Request): Promise<Response> {
    if (request.method === "DELETE") {
      await this.reset();
      return Response.json({ ok: true });
    }
    // ...rest unchanged
  }
}`}
				highlightLines={[4, 5, 6, 7, 10, 11, 12]}
			/>
			<p>
				Wrangler picks up the change via HMR, the DO reloads (in dev), and
				you can <code>curl -X DELETE http://localhost:8787/counter/demo</code>{" "}
				to reset. From inside another agent,{" "}
				<code>
					(await getAgent&lt;CounterAgent&gt;(env.COUNTER_AGENT,
					&quot;demo&quot;)).reset()
				</code>{" "}
				would invoke the same method over Workers RPC with full type
				inference.
			</p>

			<h2>Deploy</h2>
			<p>
				Commit what you have, then:
			</p>
			<CodeBlock
				lang="sh"
				code={`git add -A && git commit -m "first counter agent"
git push
bun run deploy`}
			/>
			<p>
				ayjnt checks that your tree is clean and in sync with origin, writes
				the pending migration into{" "}
				<code>.ayjnt/migrations.json</code>, and then hands off to{" "}
				<code>wrangler deploy</code>. The first deploy will prompt you to{" "}
				<code>wrangler login</code>.
			</p>
			<Callout kind="warn" title="Commit the lockfile">
				If <code>ayjnt build</code> staged a new migration but you
				haven&apos;t committed <code>.ayjnt/migrations.json</code>,{" "}
				<code>ayjnt deploy</code> will refuse to run. Commit it,{" "}
				<code>git push</code>, then retry. This is the git-safety contract
				that keeps two developers from racing divergent schemas to prod.
			</Callout>

			<h2>What you just did</h2>
			<ul>
				<li>
					Created one Durable Object class (CounterAgent), bound at{" "}
					<code>/counter/:instance</code>.
				</li>
				<li>
					Registered it as a DO binding in the generated{" "}
					<code>wrangler.jsonc</code>, with an automatic migration entry in
					the lockfile.
				</li>
				<li>
					Exercised state persistence — each <code>/counter/&lt;x&gt;</code>{" "}
					is a separate DO.
				</li>
				<li>
					Added a public method that&apos;s both HTTP-accessible via
					<code>onRequest</code> and RPC-accessible via{" "}
					<code>getAgent</code>.
				</li>
				<li>Deployed it to production behind a git-safety check.</li>
			</ul>
			<p>
				Next:{" "}
				<a href="/docs/getting-started/project-anatomy" className="link-underline">
					Project anatomy
				</a>{" "}
				walks you through the <code>.ayjnt/</code> directory so you know
				which files you own and which the framework regenerates.
			</p>
		</DocPageShell>
	);
}
