// GENERATED by ayjnt — do not edit.
import type ReportsAgent from "../agents/admin/reports/agent.ts";
import type CatalogAgent from "../agents/catalog/agent.ts";
import type OrdersAgent from "../agents/orders/agent.ts";
import type UsersAgent from "../agents/users/agent.ts";

/**
 * Every Durable Object binding derived from the file tree under agents/.
 * Extend this with your own wrangler bindings (KV, R2, vars):
 *
 *   import type { GeneratedEnv } from "@ayjnt/env";
 *   type Env = GeneratedEnv & { KV: KVNamespace };
 */
export type GeneratedEnv = {
  REPORTS_AGENT: DurableObjectNamespace<ReportsAgent>;
  CATALOG_AGENT: DurableObjectNamespace<CatalogAgent>;
  ORDERS_AGENT: DurableObjectNamespace<OrdersAgent>;
  USERS_AGENT: DurableObjectNamespace<UsersAgent>;
};
