// GENERATED by ayjnt — do not edit.
import type ResearchAgent from "../agents/research/agent.ts";

/**
 * Every Durable Object binding derived from the file tree under agents/,
 * plus any feature-flag-derived bindings (BROWSER, LOADER, AI, etc.) the
 * codegen added because of imports it detected.
 *
 * Extend this with your own wrangler bindings (KV, R2, vars):
 *
 *   import type { GeneratedEnv } from "@ayjnt/env";
 *   type Env = GeneratedEnv & { KV: KVNamespace };
 */
export type GeneratedEnv = {
  RESEARCH_AGENT: DurableObjectNamespace<ResearchAgent>;
  /** Browser Rendering binding. Added when any agent imports from "ayjnt/browser". */
  BROWSER: Fetcher;
  /** Worker Loader binding for sandboxed CDP execution. Added with the browser feature. */
  LOADER: WorkerLoader;
  /** Workers AI binding used by the browser tools' code-mode model. Added with the browser feature. */
  AI: Ai;
};
