// GENERATED by ayjnt — do not edit.
// Typed useAgent hook for OrdersAgent at /orders.
import {
  useAgent as useAgentUpstream,
  type UseAgentOptions,
} from "agents/react";
import type OrdersAgent from "../../../agents/orders/agent.ts";

/** The agent class, re-exported so callers can `import type { OrdersAgent } from "@ayjnt/...".` */
export type { default as OrdersAgent } from "../../../agents/orders/agent.ts";

type Instance = InstanceType<typeof OrdersAgent>;
type DefaultState = Instance extends { state: infer S } ? S : unknown;

/**
 * React hook bound to OrdersAgent. Derives `basePath` from the agent's
 * route prefix "/orders" and an instance name taken from the current
 * URL. Pass `name` to override the instance:
 *
 *   const agent = useAgent();                       // URL-derived
 *   const agent = useAgent({ name: "room-42" });    // explicit
 *   const agent = useAgent<MyState>();              // custom State type
 */
export function useAgent<State = DefaultState>(
  options?: Omit<UseAgentOptions<State>, "agent" | "basePath"> & {
    /** Override the URL-derived instance name. */
    name?: string;
  },
): ReturnType<typeof useAgentUpstream<State>> {
  const { name: overrideName, ...rest } = options ?? {};
  const instanceName = overrideName ?? deriveInstance();
  return useAgentUpstream<State>({
    agent: "OrdersAgent",
    basePath: "orders" + "/" + instanceName,
    ...rest,
  });
}

/**
 * Pull the instance name out of window.location.pathname.
 *
 *   /orders                        → "default"
 *   /orders/room-42                → "room-42"
 *   /orders/room-42/anything-else  → "room-42"
 */
function deriveInstance(): string {
  if (typeof window === "undefined") return "default";
  const prefix = "/orders";
  const p = window.location.pathname;
  if (p !== prefix && !p.startsWith(prefix + "/")) return "default";
  const remainder = p.slice(prefix.length);
  const parts = remainder.split("/").filter(Boolean);
  return parts[0] ?? "default";
}
