// GENERATED by ayjnt — do not edit.
import type OrdersAgent from "../agents/orders/agent.ts";
import type OrdersProcessing from "../agents/orders/workflow.ts";

/**
 * Every Durable Object binding derived from the file tree under agents/,
 * plus any feature-flag-derived bindings (BROWSER, LOADER, AI, etc.) the
 * codegen added because of imports it detected.
 *
 * Extend this with your own wrangler bindings (KV, R2, vars):
 *
 *   import type { GeneratedEnv } from "@ayjnt/env";
 *   type Env = GeneratedEnv & { KV: KVNamespace };
 */
export type GeneratedEnv = {
  ORDERS_AGENT: DurableObjectNamespace<OrdersAgent>;
  /** Workflow binding for OrdersProcessing (class lives at /Users/southclock/Documents/Projects/ayjnt/examples/workflows/agents/orders/workflow.ts). */
  ORDERS_PROCESSING: Workflow;
};
