import { describe, expect, test } from "bun:test";
import {
  DEFAULT_PORT,
  defaultDataDir,
  parseDevVars,
  parseGeneratedConfig,
  resolveUrl,
  splitBinaryArgs,
  translateStubError,
} from "./host.ts";
import { parseRunArgs } from "./run.ts";
import type { AgentEntry } from "../core/types.ts";
import { parseCompileArgs, workerdPackageFor } from "./compile.ts";
import { confinePath, isSchemaLibraryObject, toJsonSchema } from "./hostTools.ts";
import { hostToolName } from "../core/hostBridge.ts";

describe("parseGeneratedConfig", () => {
  test("strips the generated header comment", () => {
    const cfg = parseGeneratedConfig(
      '// GENERATED by ayjnt — do not edit.\n{ "name": "app" }\n',
    );
    expect(cfg.name).toBe("app");
  });

  test("keeps a // inside a string value intact", () => {
    // Only whole-line comments are stripped. A naive `//`-to-end-of-line strip
    // would corrupt any URL a user put in `vars`.
    const cfg = parseGeneratedConfig(
      '// header\n{ "name": "app", "vars": { "API": "https://example.com/x" } }',
    );
    expect((cfg.vars as Record<string, string>)["API"]).toBe(
      "https://example.com/x",
    );
  });

  test("reads the bindings the local runtime cares about", () => {
    const cfg = parseGeneratedConfig(`// h
{
  "name": "app",
  "durable_objects": { "bindings": [{ "name": "CHAT_AGENT", "class_name": "ChatAgent" }] },
  "workflows": [{ "name": "importer", "binding": "IMPORTER", "class_name": "Importer" }],
  "assets": { "directory": "../assets", "binding": "ASSETS", "html_handling": "none" }
}`);
    expect(cfg.durable_objects?.bindings[0]?.class_name).toBe("ChatAgent");
    expect(cfg.workflows?.[0]?.binding).toBe("IMPORTER");
    expect(cfg.assets?.html_handling).toBe("none");
  });
});

describe("parseDevVars", () => {
  test("parses simple assignments and skips comments and blanks", () => {
    expect(parseDevVars("A=1\n\n# note\nB=two\n")).toEqual({
      A: "1",
      B: "two",
    });
  });

  test("strips one layer of matching quotes", () => {
    expect(parseDevVars(`A="quoted"\nB='single'`)).toEqual({
      A: "quoted",
      B: "single",
    });
  });

  test("keeps = inside a value", () => {
    expect(parseDevVars("TOKEN=abc=def==")).toEqual({ TOKEN: "abc=def==" });
  });

  test("ignores a line with no key", () => {
    expect(parseDevVars("=novalue\nA=1")).toEqual({ A: "1" });
  });
});

describe("resolveUrl", () => {
  test("resolves a path against the origin", () => {
    expect(resolveUrl("http://localhost:8787", "/counter/demo")).toBe(
      "http://localhost:8787/counter/demo",
    );
  });

  test("adds the missing leading slash", () => {
    expect(resolveUrl("http://localhost:8787", "counter")).toBe(
      "http://localhost:8787/counter",
    );
  });

  test("leaves an absolute URL alone", () => {
    expect(resolveUrl("http://localhost:8787", "https://example.com/x")).toBe(
      "https://example.com/x",
    );
  });
});

describe("defaultDataDir", () => {
  test("is per-app, so two apps never share Durable Object storage", () => {
    expect(defaultDataDir("app-a")).not.toBe(defaultDataDir("app-b"));
  });

  test("is absolute and includes the worker name", () => {
    const dir = defaultDataDir("my-worker");
    expect(dir).toStartWith("/");
    expect(dir).toContain("my-worker");
    expect(dir).toContain("ayjnt");
  });
});

describe("parseRunArgs", () => {
  test("defaults to no port override and read-only host tools", () => {
    const a = parseRunArgs([]);
    expect(a.port).toBeUndefined();
    expect(a.allowWrite).toBe(false);
    expect(a.allowExec).toBe(false);
    expect(a.cliArgv).toEqual([]);
  });

  test("accepts both --flag value and --flag=value", () => {
    expect(parseRunArgs(["--port", "9000"]).port).toBe(9000);
    expect(parseRunArgs(["--port=9000"]).port).toBe(9000);
  });

  test("passes everything after -- to cli.ts", () => {
    const a = parseRunArgs(["--port", "9000", "--", "--mine", "x"]);
    expect(a.port).toBe(9000);
    expect(a.cliArgv).toEqual(["--mine", "x"]);
  });

  test("rejects an unknown flag rather than silently ignoring it", () => {
    // A mistyped `--prot 8787` handed to cli.ts would bind the default port
    // and look like it worked.
    expect(() => parseRunArgs(["--nope"])).toThrow(/unknown option/);
    expect(() => parseRunArgs(["--prot", "8787"])).toThrow(/unknown option/);
  });

  test("passes positionals through to cli.ts without needing --", () => {
    // `bun run start -- list` has its `--` eaten by Bun, so ayjnt receives
    // `run list`. Rejecting that broke the documented invocation.
    expect(parseRunArgs(["list"]).cliArgv).toEqual(["list"]);
    expect(parseRunArgs(["add", "hello", "world"]).cliArgv).toEqual([
      "add",
      "hello",
      "world",
    ]);
  });

  test("mixes flags and positionals in either order", () => {
    const a = parseRunArgs(["--port", "9000", "add", "hi"]);
    expect(a.port).toBe(9000);
    expect(a.cliArgv).toEqual(["add", "hi"]);

    const b = parseRunArgs(["add", "hi", "--port", "9000"]);
    expect(b.port).toBe(9000);
    expect(b.cliArgv).toEqual(["add", "hi"]);
  });

  test("positionals and post-separator args both reach cli.ts, in order", () => {
    const a = parseRunArgs(["tool", "--port", "9000", "--", "--json"]);
    expect(a.port).toBe(9000);
    expect(a.cliArgv).toEqual(["tool", "--json"]);
  });

  test("rejects a non-numeric or out-of-range port", () => {
    expect(() => parseRunArgs(["--port", "abc"])).toThrow(/--port/);
    expect(() => parseRunArgs(["--port", "99999"])).toThrow(/--port/);
  });

  test("rejects a flag whose value is missing", () => {
    expect(() => parseRunArgs(["--port"])).toThrow(/requires a value/);
  });

  test("allows port 0 for an ephemeral port", () => {
    expect(parseRunArgs(["--port", "0"]).port).toBe(0);
  });

  test("host effect flags are opt-in", () => {
    const a = parseRunArgs(["--allow-host-writes", "--allow-host-exec"]);
    expect(a.allowWrite).toBe(true);
    expect(a.allowExec).toBe(true);
  });
});

describe("parseCompileArgs", () => {
  test("embeds workerd by default", () => {
    expect(parseCompileArgs([]).embedWorkerd).toBe(true);
  });

  test("--no-embed-workerd opts out", () => {
    expect(parseCompileArgs(["--no-embed-workerd"]).embedWorkerd).toBe(false);
  });

  test("reads outfile, target and codegen flags", () => {
    const a = parseCompileArgs([
      "--outfile",
      "./dist/app",
      "--target=bun-linux-x64",
      "--bytecode",
      "--minify",
    ]);
    expect(a.outfile).toBe("./dist/app");
    expect(a.target).toBe("bun-linux-x64");
    expect(a.bytecode).toBe(true);
    expect(a.minify).toBe(true);
  });

  test("rejects an unknown flag", () => {
    expect(() => parseCompileArgs(["--wat"])).toThrow(/unknown option/);
  });
});

describe("workerdPackageFor", () => {
  test("maps Bun compile targets to workerd platform packages", () => {
    expect(workerdPackageFor("bun-linux-x64")).toBe(
      "@cloudflare/workerd-linux-64",
    );
    expect(workerdPackageFor("bun-darwin-arm64")).toBe(
      "@cloudflare/workerd-darwin-arm64",
    );
    expect(workerdPackageFor("bun-windows-x64")).toBe(
      "@cloudflare/workerd-windows-64",
    );
  });

  test("ignores the baseline/modern suffix, which is a Bun concern only", () => {
    expect(workerdPackageFor("bun-linux-x64-baseline")).toBe(
      "@cloudflare/workerd-linux-64",
    );
    expect(workerdPackageFor("bun-linux-x64-modern")).toBe(
      "@cloudflare/workerd-linux-64",
    );
  });

  test("defaults to the host platform", () => {
    expect(workerdPackageFor()).toContain("@cloudflare/workerd-");
  });

  test("throws for a target with no workerd build", () => {
    expect(() => workerdPackageFor("bun-plan9-sparc")).toThrow(/no workerd build/);
  });
});

describe("hostToolName", () => {
  test("namespaces by route so two agents can share an export name", () => {
    expect(hostToolName("/research", "search")).toBe("research__search");
    expect(hostToolName("/notes", "search")).toBe("notes__search");
  });

  test("flattens nested routes into a provider-safe name", () => {
    // Providers constrain tool names to [a-zA-Z0-9_-].
    expect(hostToolName("/admin/users", "list")).toBe("admin_users__list");
    expect(hostToolName("/admin/users", "list")).toMatch(/^[a-zA-Z0-9_-]+$/);
  });
});

describe("toJsonSchema", () => {
  test("converts a zod schema rather than passing it through", async () => {
    // Regression: zod 4 schemas expose their own `.type`, so an "is this
    // already JSON Schema?" check that looks at `type` first matches the live
    // schema object and hands it to Miniflare, which rejects it.
    const { z } = await import("zod");
    const out = (await toJsonSchema(
      z.object({ dir: z.string(), depth: z.number().optional() }),
    )) as Record<string, unknown>;
    expect(out["type"]).toBe("object");
    expect(Object.keys(out["properties"] as object)).toEqual(["dir", "depth"]);
    // Optional fields must stay optional in the input view.
    expect(out["required"]).toEqual(["dir"]);
    expect(JSON.parse(JSON.stringify(out))).toEqual(out);
  });

  test("passes a literal JSON Schema through untouched", async () => {
    const schema = { type: "object", properties: { a: { type: "string" } } };
    expect(await toJsonSchema(schema)).toBe(schema);
  });

  test("falls back to a permissive schema for junk", async () => {
    expect(await toJsonSchema(undefined)).toEqual({
      type: "object",
      additionalProperties: true,
    });
    expect(await toJsonSchema("nope")).toEqual({
      type: "object",
      additionalProperties: true,
    });
  });
});

describe("isSchemaLibraryObject", () => {
  test("recognizes a zod schema", async () => {
    const { z } = await import("zod");
    expect(isSchemaLibraryObject(z.object({}))).toBe(true);
  });

  test("does not mistake a plain JSON Schema for a library object", () => {
    expect(isSchemaLibraryObject({ type: "object" })).toBe(false);
  });
});

describe("confinePath", () => {
  test("resolves a relative path inside the root", () => {
    expect(confinePath("/srv/data", "notes.txt")).toBe("/srv/data/notes.txt");
    expect(confinePath("/srv/data", "sub/notes.txt")).toBe(
      "/srv/data/sub/notes.txt",
    );
  });

  test("rejects traversal out of the root", () => {
    // The whole point: a model-supplied path is untrusted input.
    expect(() => confinePath("/srv/data", "../etc/passwd")).toThrow(/escapes/);
    expect(() => confinePath("/srv/data", "a/../../b")).toThrow(/escapes/);
  });

  test("rejects an absolute path that lands outside the root", () => {
    expect(() => confinePath("/srv/data", "/etc/passwd")).toThrow(/escapes/);
  });

  test("does not fall for a sibling directory sharing a name prefix", () => {
    // A naive startsWith check would accept /srv/data-evil as inside /srv/data.
    expect(() => confinePath("/srv/data", "../data-evil/x")).toThrow(/escapes/);
  });
});

describe("splitBinaryArgs", () => {
  test("claims nothing by default", () => {
    const a = splitBinaryArgs([]);
    expect(a).toEqual({ allowWrite: false, allowExec: false, cliArgv: [] });
  });

  test("consumes a value flag AND its value", () => {
    // Regression: the first version dropped `--port` but left `8787` behind,
    // which cli.ts then read as a subcommand.
    const a = splitBinaryArgs(["--port", "8787", "list"]);
    expect(a.port).toBe(8787);
    expect(a.cliArgv).toEqual(["list"]);
  });

  test("handles flags before and after the user's own args", () => {
    expect(splitBinaryArgs(["--port", "9000", "list"]).cliArgv).toEqual(["list"]);
    expect(splitBinaryArgs(["list", "--port", "9000"]).cliArgv).toEqual(["list"]);
  });

  test("accepts the = form", () => {
    const a = splitBinaryArgs(["--port=9000", "--data-dir=/tmp/x", "go"]);
    expect(a.port).toBe(9000);
    expect(a.dataDir).toBe("/tmp/x");
    expect(a.cliArgv).toEqual(["go"]);
  });

  test("passes unknown flags to cli.ts rather than rejecting them", () => {
    // The binary is the user's program; only four flags are ours.
    const a = splitBinaryArgs(["--verbose", "--mine=1", "run"]);
    expect(a.cliArgv).toEqual(["--verbose", "--mine=1", "run"]);
  });

  test("an explicit -- hands the whole remainder to cli.ts", () => {
    // So a cli.ts that wants its own --port can still have one.
    const a = splitBinaryArgs(["--port", "9000", "--", "--port", "1234"]);
    expect(a.port).toBe(9000);
    expect(a.cliArgv).toEqual(["--port", "1234"]);
  });

  test("reads the host-effect flags", () => {
    const a = splitBinaryArgs(["--allow-host-writes", "--allow-host-exec", "x"]);
    expect(a.allowWrite).toBe(true);
    expect(a.allowExec).toBe(true);
    expect(a.cliArgv).toEqual(["x"]);
  });

  test("rejects a nonsense port", () => {
    expect(() => splitBinaryArgs(["--port", "abc"])).toThrow(/--port/);
    expect(() => splitBinaryArgs(["--port", "70000"])).toThrow(/--port/);
  });
});

describe("translateStubError", () => {
  const agent = {
    className: "NotesAgent",
    routePath: "/admin/notes",
  } as AgentEntry;

  function proxyAssertion(): Error {
    // What miniflare actually throws when an agent method rejects and the call
    // came from the host: it asserts `!isClientError(status)` before reading the
    // body, so the real message is gone by the time we see anything.
    const err = new Error("false == true");
    (err as { code?: string }).code = "ERR_ASSERTION";
    return err;
  }

  test("replaces the opaque assertion with an actionable explanation", () => {
    const out = translateStubError(proxyAssertion(), agent, "addNote");
    expect(out.message).toContain("NotesAgent.addNote() threw inside the agent");
    expect(out.message).toContain("Miniflare limitation");
    expect(out.message).not.toContain("false == true");
  });

  test("suggests the camelized accessor path for the HTTP fallback", () => {
    const out = translateStubError(proxyAssertion(), agent, "addNote");
    expect(out.message).toContain("agents.admin.notes(...).fetch()");
  });

  test("passes a genuine application error through untouched", () => {
    // Only the specific miniflare assertion is special-cased. Anything else is
    // a real error and must not be reworded.
    const real = new Error("network unreachable");
    expect(translateStubError(real, agent, "addNote")).toBe(real);
  });

  test("does not swallow an unrelated assertion error", () => {
    const other = new Error("expected 1 to equal 2");
    (other as { code?: string }).code = "ERR_ASSERTION";
    expect(translateStubError(other, agent, "x").message).toBe(
      "expected 1 to equal 2",
    );
  });

  test("wraps a non-Error throw", () => {
    expect(translateStubError("just a string", agent, "x")).toBeInstanceOf(Error);
  });
});

describe("DEFAULT_PORT", () => {
  test("matches wrangler dev so muscle memory carries over", () => {
    expect(DEFAULT_PORT).toBe(8787);
  });
});
