// GENERATED by ayjnt — do not edit.
import type ConferenceRoom from "../agents/room/agent.ts";
import type Transcriber from "../agents/transcriber/agent.ts";

/**
 * Every Durable Object binding derived from the file tree under agents/,
 * plus any feature-flag-derived bindings (BROWSER, LOADER, AI, etc.) the
 * codegen added because of imports it detected.
 *
 * Extend this with your own wrangler bindings (KV, R2, vars):
 *
 *   import type { GeneratedEnv } from "@ayjnt/env";
 *   type Env = GeneratedEnv & { KV: KVNamespace };
 */
export type GeneratedEnv = {
  CONFERENCE_ROOM: DurableObjectNamespace<ConferenceRoom>;
  TRANSCRIBER: DurableObjectNamespace<Transcriber>;
  /** Workers AI binding used by Voice agents' STT/TTS providers. */
  AI: Ai;
};
