// GENERATED by ayjnt — do not edit.
// Typed useAgent hook for NotesAgent at /notes.
import {
  useAgent as __ayjntUseAgentUpstream,
  type UseAgentOptions,
} from "agents/react";
import type __AyjntAgentClass from "../../../agents/notes/agent.ts";

/** The agent class, re-exported so callers can `import type { NotesAgent } from "@ayjnt/...".` */
export type { default as NotesAgent } from "../../../agents/notes/agent.ts";

type __AyjntInstance = InstanceType<typeof __AyjntAgentClass>;
type __AyjntState = __AyjntInstance extends { state: infer S } ? S : unknown;

/**
 * React hook bound to NotesAgent. Derives `basePath` from the agent's
 * route prefix "/notes" and an instance name taken from the current
 * URL. Pass `name` to override the instance:
 *
 *   const agent = useAgent();                       // URL-derived
 *   const agent = useAgent({ name: "room-42" });    // explicit instance
 *
 * The return type carries through to `agent.stub.<method>(...)` and
 * `agent.call("<method>", [...])` — every method on NotesAgent
 * decorated with `@callable()` from "agents" is reachable with full
 * argument and return-type checking.
 *
 * The hook is bound to NotesAgent's own state shape — there's no
 * State generic. Renaming a field on the agent's State propagates here
 * automatically on the next `ayjnt build`. If you genuinely need a
 * different shape on the client side, narrow at the use site instead
 * of overriding the type.
 */
export function useAgent(
  options?: Omit<UseAgentOptions<__AyjntState>, "agent" | "basePath"> & {
    /** Override the URL-derived instance name. */
    name?: string;
  },
): ReturnType<typeof __ayjntUseAgentUpstream<__AyjntInstance, __AyjntState>> {
  const { name: overrideName, ...rest } = options ?? {};
  const instanceName = overrideName ?? __ayjntDeriveInstance();
  // Re-encode: the derived name is the DECODED segment (matching the
  // worker), so embedding it raw would let a name containing "/", "?" or
  // "#" be re-parsed as URL structure and bind the UI to the wrong DO.
  return __ayjntUseAgentUpstream<__AyjntInstance, __AyjntState>({
    agent: "NotesAgent",
    basePath: "notes" + "/" + encodeURIComponent(instanceName),
    ...rest,
  });
}

/**
 * Pull the instance name out of window.location.pathname. Segments are
 * percent-decoded to mirror the worker's route matcher, so the UI binds
 * to the same Durable Object the server dispatches to.
 *
 *   /notes                        → "default"
 *   /notes/room-42                → "room-42"
 *   /notes/room-42/anything-else  → "room-42"
 */
function __ayjntDeriveInstance(): string {
  if (typeof window === "undefined") return "default";
  const prefix: string[] = ["notes"];
  const segments = window.location.pathname
    .split("/")
    .filter(Boolean)
    .map((s) => {
      try {
        return decodeURIComponent(s);
      } catch {
        return s;
      }
    });
  for (let i = 0; i < prefix.length; i++) {
    if (segments[i] !== prefix[i]) return "default";
  }
  return segments[prefix.length] ?? "default";
}
