// GENERATED by ayjnt — do not edit.
import type ChatVoice from "../agents/chat/agent.ts";

/**
 * Every Durable Object binding derived from the file tree under agents/,
 * plus any feature-flag-derived bindings (BROWSER, LOADER, AI, etc.) the
 * codegen added because of imports it detected.
 *
 * Extend this with your own wrangler bindings (KV, R2, vars):
 *
 *   import type { GeneratedEnv } from "@ayjnt/env";
 *   type Env = GeneratedEnv & { KV: KVNamespace };
 */
export type GeneratedEnv = {
  CHAT_VOICE: DurableObjectNamespace<ChatVoice>;
  /** Workers AI binding used by Voice agents' STT/TTS providers. */
  AI: Ai;
};
