// GENERATED by ayjnt — do not edit.
import type NotesAgent from "../agents/notes/agent.ts";

/**
 * Every Durable Object binding derived from the file tree under agents/.
 * Extend this with your own wrangler bindings (KV, R2, vars):
 *
 *   import type { GeneratedEnv } from "@ayjnt/env";
 *   type Env = GeneratedEnv & { KV: KVNamespace };
 */
export type GeneratedEnv = {
  NOTES_AGENT: DurableObjectNamespace<NotesAgent>;
};
