// Client-side code generation — tsconfig for path aliases, env.d.ts for the
// generated Env type, and one typed useAgent hook per agent.
//
// Files land in <root>/.ayjnt/ alongside migrations.json and dist/. The
// user gitignores .ayjnt/* except migrations.json. To pick up the path
// aliases, their own tsconfig.json needs to:
//
//   {
//     "extends": "./.ayjnt/tsconfig.json",
//     ...
//   }
//
// After that, `import { useAgent } from "@ayjnt/chat"` resolves to
// .ayjnt/client/chat/index.tsx, and `import type { GeneratedEnv } from
// "@ayjnt/env"` resolves to .ayjnt/env.d.ts.

import * as path from "node:path";
import type { AgentEntry, Manifest } from "../core/types.ts";

/**
 * tsconfig.json the user extends to get path aliases for generated code.
 *
 * Paths are resolved relative to the file that defines them (TS behavior),
 * so `./client/*` here means .ayjnt/client/* — works regardless of where
 * the extending tsconfig lives in the project tree.
 */
export function generateTsconfig(): string {
  const config = {
    compilerOptions: {
      paths: {
        "@ayjnt/env": ["./env.d.ts"],
        "@ayjnt/*": ["./client/*"],
      },
    },
  };
  const header =
    "// GENERATED by ayjnt — do not edit. Extended by your tsconfig.json.\n";
  return header + JSON.stringify(config, null, 2) + "\n";
}

/**
 * Declares the GeneratedEnv type with every agent's DO binding. Extend it
 * with your own KV/R2/etc bindings:
 *
 *   import type { GeneratedEnv } from "@ayjnt/env";
 *   type Env = GeneratedEnv & { KV: KVNamespace };
 *
 * @param manifest  scan result
 * @param outPath   absolute path to the env.d.ts we're emitting (used for
 *                  computing relative imports to agent source files)
 */
export function generateEnvTypes(
  manifest: Manifest,
  outPath: string,
): string {
  const outDir = path.dirname(path.resolve(outPath));

  const agentImports = manifest.agents
    .map((a) => {
      const rel = toImportSpec(outDir, a.sourceFile);
      return `import type ${a.className} from "${rel}";`;
    })
    .join("\n");

  const workflowImports = manifest.workflows
    .map((w) => {
      const rel = toImportSpec(outDir, w.sourceFile);
      return `import type ${w.className} from "${rel}";`;
    })
    .join("\n");

  const imports = [agentImports, workflowImports].filter(Boolean).join("\n");

  const agentFields = manifest.agents
    .map(
      (a) =>
        `  ${a.binding}: DurableObjectNamespace<${a.className}>;`,
    )
    .join("\n");

  // Workflow bindings — runtime type is `Workflow` from
  // cloudflare:workers, parameterised on the workflow's params type.
  // We don't know the params shape from scan-level information so we
  // default to `unknown`; users who want stricter typing can `as`-cast
  // at the call site.
  const workflowFields = manifest.workflows
    .map(
      (w) =>
        `  /** Workflow binding for ${w.className} (class lives at ${w.sourceFile}). */\n  ${w.binding}: Workflow;`,
    )
    .join("\n");

  // Feature-flag-derived bindings. Mirror exactly what generateWrangler
  // adds to wrangler.jsonc, so the runtime types and the binding shape
  // stay in lockstep.
  const featureFields: string[] = [];
  if (manifest.features.browser) {
    // Cloudflare's Browser Rendering binding is a Fetcher (we POST to
    // it; the SDK abstracts the protocol). The Worker Loader binding
    // exposes the runtime that runs sandboxed CDP code; its type
    // comes from @cloudflare/workers-types. The AI binding is shared
    // with Workers AI.
    featureFields.push(`  /** Browser Rendering binding. Added when any agent imports from "ayjnt/browser". */`);
    featureFields.push(`  BROWSER: Fetcher;`);
    featureFields.push(`  /** Worker Loader binding for sandboxed CDP execution. Added with the browser feature. */`);
    featureFields.push(`  LOADER: WorkerLoader;`);
    featureFields.push(`  /** Workers AI binding used by the browser tools' code-mode model. Added with the browser feature. */`);
    featureFields.push(`  AI: Ai;`);
  }
  if (manifest.features.email) {
    // Cloudflare's send_email binding gives us a SendEmail object.
    // Imported from cloudflare:email (built-in module).
    featureFields.push(`  /** Email send binding. Added when any agent implements onEmail(email). Used by this.sendEmail()/this.replyToEmail(). */`);
    featureFields.push(`  EMAIL: SendEmail;`);
  }
  // Voice agents need the AI binding for STT/TTS. Already added by the
  // browser feature, so only emit it here if browser is off.
  if (manifest.features.voice && !manifest.features.browser) {
    featureFields.push(`  /** Workers AI binding used by Voice agents' STT/TTS providers. */`);
    featureFields.push(`  AI: Ai;`);
  }

  const allFields = [agentFields, workflowFields, ...featureFields]
    .filter(Boolean)
    .join("\n");

  return `// GENERATED by ayjnt — do not edit.
${imports || "// (no agents discovered)"}

/**
 * Every Durable Object binding derived from the file tree under agents/,
 * plus any feature-flag-derived bindings (BROWSER, LOADER, AI, etc.) the
 * codegen added because of imports it detected.
 *
 * Extend this with your own wrangler bindings (KV, R2, vars):
 *
 *   import type { GeneratedEnv } from "@ayjnt/env";
 *   type Env = GeneratedEnv & { KV: KVNamespace };
 */
export type GeneratedEnv = {
${allFields || "  // no agents"}
};
`;
}

/**
 * Typed useAgent hook for one agent. The user imports:
 *
 *   import { useAgent } from "@ayjnt/<route>";
 *
 * The hook pre-fills `basePath` from the agent's route prefix + an
 * instance name derived from the current URL (first path segment after
 * the prefix). Override with `useAgent({ name: "custom-id" })`.
 *
 * @param agent     one entry from the manifest
 * @param outPath   absolute path to the client/<route>/index.tsx we're
 *                  emitting (used for the relative import to agent.ts)
 */
export function generateClientHook(
  agent: AgentEntry,
  outPath: string,
): string {
  // Voice agents need a different hook entirely — `useVoiceAgent` from
  // `@cloudflare/voice/react` instead of `useAgent` from `agents/react`,
  // and a custom transport that connects via ayjnt's URL shape rather
  // than the SDK's partysocket-derived default.
  return agent.isVoice
    ? generateVoiceHook(agent, outPath)
    : generateRegularHook(agent, outPath);
}

/**
 * Generated typed hook for a regular Agent. Wraps the upstream
 * `useAgent` from `agents/react` with the agent class pre-bound and
 * the basePath wired to the ayjnt-shaped URL.
 */
function generateRegularHook(agent: AgentEntry, outPath: string): string {
  const outDir = path.dirname(path.resolve(outPath));
  const agentImport = toImportSpec(outDir, agent.sourceFile);
  const routePath = agent.routePath;
  const className = agent.className;

  return `// GENERATED by ayjnt — do not edit.
// Typed useAgent hook for ${className} at ${routePath}.
import {
  useAgent as useAgentUpstream,
  type UseAgentOptions,
} from "agents/react";
import type ${className} from "${agentImport}";

/** The agent class, re-exported so callers can \`import type { ${className} } from "@ayjnt/...".\` */
export type { default as ${className} } from "${agentImport}";

type Instance = InstanceType<typeof ${className}>;
type AgentState = Instance extends { state: infer S } ? S : unknown;

/**
 * React hook bound to ${className}. Derives \`basePath\` from the agent's
 * route prefix "${routePath}" and an instance name taken from the current
 * URL. Pass \`name\` to override the instance:
 *
 *   const agent = useAgent();                       // URL-derived
 *   const agent = useAgent({ name: "room-42" });    // explicit instance
 *
 * The return type carries through to \`agent.stub.<method>(...)\` and
 * \`agent.call("<method>", [...])\` — every method on ${className}
 * decorated with \`@callable()\` from "agents" is reachable with full
 * argument and return-type checking.
 *
 * The hook is bound to ${className}'s own state shape — there's no
 * State generic. Renaming a field on the agent's State propagates here
 * automatically on the next \`ayjnt build\`. If you genuinely need a
 * different shape on the client side, narrow at the use site instead
 * of overriding the type.
 */
export function useAgent(
  options?: Omit<UseAgentOptions<AgentState>, "agent" | "basePath"> & {
    /** Override the URL-derived instance name. */
    name?: string;
  },
): ReturnType<typeof useAgentUpstream<Instance, AgentState>> {
  const { name: overrideName, ...rest } = options ?? {};
  const instanceName = overrideName ?? deriveInstance();
  return useAgentUpstream<Instance, AgentState>({
    agent: ${JSON.stringify(className)},
    basePath: ${JSON.stringify(routePath.slice(1))} + "/" + instanceName,
    ...rest,
  });
}

/**
 * Pull the instance name out of window.location.pathname.
 *
 *   /${routePath.slice(1)}                        → "default"
 *   /${routePath.slice(1)}/room-42                → "room-42"
 *   /${routePath.slice(1)}/room-42/anything-else  → "room-42"
 */
function deriveInstance(): string {
  if (typeof window === "undefined") return "default";
  const prefix = ${JSON.stringify(routePath)};
  const p = window.location.pathname;
  if (p !== prefix && !p.startsWith(prefix + "/")) return "default";
  const remainder = p.slice(prefix.length);
  const parts = remainder.split("/").filter(Boolean);
  return parts[0] ?? "default";
}
`;
}

/**
 * Generated typed hook for a voice agent (one built with
 * `withVoice(Agent)` from `@cloudflare/voice`).
 *
 * Wraps `useAyjntVoiceAgent` from `ayjnt/voice/client` — which is in
 * turn a thin wrapper around `useVoiceAgent` from
 * `@cloudflare/voice/react` that uses an `AyjntVoiceTransport` to
 * connect over ayjnt's URL shape (`/<route>/<instance>`) instead of
 * the SDK's default partysocket-derived `/agents/<kebab>/<instance>`
 * path.
 *
 * The user calls a bare `useVoiceAgent()` in their `app.tsx`; the
 * agent class name and route prefix are pre-bound here at codegen
 * time. No URL hand-wiring at the call site.
 */
function generateVoiceHook(agent: AgentEntry, outPath: string): string {
  const outDir = path.dirname(path.resolve(outPath));
  const agentImport = toImportSpec(outDir, agent.sourceFile);
  const routePath = agent.routePath;
  const className = agent.className;

  return `// GENERATED by ayjnt — do not edit.
// Typed useVoiceAgent hook for ${className} at ${routePath}.
//
// ${className} is built with the \`withVoice(...)\` mixin from
// \`@cloudflare/voice\`, so we route React calls through ayjnt's
// custom voice transport (URL: /<route>/<instance>) rather than the
// SDK's default \`/agents/<kebab>/<name>\` path.
import { AyjntVoiceTransport, useAyjntVoiceAgent } from "ayjnt/voice/client";
import type ${className} from "${agentImport}";

/** The agent class, re-exported so callers can \`import type { ${className} } from "@ayjnt/...".\` */
export type { default as ${className} } from "${agentImport}";

// Re-exported as a value so callers writing framework-agnostic code
// (no React) can construct their own transport against ayjnt's URL
// shape.
export { AyjntVoiceTransport };

/**
 * React hook bound to ${className}. Connects over WebSocket to the
 * voice agent at ${routePath} and drives the
 * \`@cloudflare/voice\` STT/TTS pipeline.
 *
 *   const v = useVoiceAgent();                         // URL-derived instance
 *   const v = useVoiceAgent({ name: "room-42" });      // explicit instance
 *
 * Returns the same shape \`useVoiceAgent\` from
 * \`@cloudflare/voice/react\` does: \`status\`, \`transcript\`,
 * \`interimTranscript\`, \`audioLevel\`, \`isMuted\`, \`startCall\`,
 * \`endCall\`, \`toggleMute\`, \`sendText\`, \`sendJSON\`, etc.
 *
 * We derive the option type from \`Parameters<typeof useAyjntVoiceAgent>\`
 * rather than re-exporting an upstream type — bunup's d.ts bundling
 * leaves relative imports unresolved in the dist artifact, so the
 * indirect route gives a cleaner consumer-side type resolution.
 */
export function useVoiceAgent(
  options?: Omit<
    Parameters<typeof useAyjntVoiceAgent>[0],
    "agent" | "routePath"
  >,
) {
  return useAyjntVoiceAgent({
    agent: ${JSON.stringify(className)},
    routePath: ${JSON.stringify(routePath)},
    ...(options ?? {}),
  });
}
`;
}

/**
 * Path in .ayjnt/client where a given agent's hook belongs. Uses routePath
 * (not folderPath) because route groups are stripped from URLs and should
 * be stripped from the import alias too.
 *
 *   routePath "/chat"        → "client/chat/index.tsx"
 *   routePath "/admin/users" → "client/admin/users/index.tsx"
 */
export function clientFileFor(agent: AgentEntry): string {
  const segments = agent.routePath.slice(1).split("/").filter(Boolean);
  return path.join("client", ...segments, "index.tsx");
}

/**
 * Directory portion of {@link clientFileFor} — the per-agent client
 * folder where both the typed hook and the generated mount wrapper live.
 *
 *   routePath "/chat"        → "client/chat"
 *   routePath "/admin/users" → "client/admin/users"
 */
export function clientDirFor(agent: AgentEntry): string {
  const segments = agent.routePath.slice(1).split("/").filter(Boolean);
  return path.join("client", ...segments);
}

/**
 * HTML shell for an agent with a co-located app.tsx. References the bundled
 * JS via a `<script src>` pointing at the Cloudflare Assets binding path
 * — we DO NOT inline the JS. Inlining broke because minified bundles
 * reliably contain `</script>` substrings (in regex literals and string
 * contents), which terminate the script tag mid-parse and dump the rest
 * as raw HTML text. Serving the bundle as a standalone asset avoids the
 * escaping problem entirely and lets Cloudflare's CDN cache it.
 */
export function generateHtmlShell(params: {
  title: string;
  /** Absolute URL path (relative to origin) where the app.js bundle lives.
   *  E.g. "/__ayjnt/counter/app.js". */
  scriptSrc: string;
}): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${escapeHtml(params.title)}</title>
</head>
<body>
<div id="root"></div>
<script type="module" src="${escapeHtml(params.scriptSrc)}"></script>
</body>
</html>
`;
}

/**
 * Flatten a route path into a filename-safe segment for the assets tree.
 *
 *   "/chat"        → "chat"
 *   "/admin/users" → "admin_users"
 *
 * Used to pick the subdirectory under .ayjnt/assets/__ayjnt/ where an
 * agent's bundled JS and HTML live, and to construct the public URL path
 * the HTML shell references.
 */
export function flattenRoute(routePath: string): string {
  return routePath.slice(1).replace(/\//g, "_");
}

function escapeHtml(s: string): string {
  return s.replace(/[&<>"']/g, (c) => ({
    "&": "&amp;",
    "<": "&lt;",
    ">": "&gt;",
    '"': "&quot;",
    "'": "&#39;",
  })[c] ?? c);
}

/**
 * Bundle an agent's app.tsx into a single browser-targeted ES module
 * string, ready to inline into a <script type="module"> tag.
 *
 * Uses Bun.build with target: "browser" so React, agents/react, and the
 * generated typed hook all get pulled in and tree-shaken. Minified to keep
 * worker bundle size down.
 *
 * ## React deduplication
 *
 * When ayjnt is symlinked into an example (the dev setup) the framework
 * has its own `node_modules/react` (used for type-checking
 * `src/runtime/voiceClient.tsx`) and so does the example. Bun.build
 * resolves `react` from each importer's location, which produces two
 * physical React copies in the bundle — one referenced by the user's
 * app.tsx and one by `ayjnt/voice/client` (which transitively imports
 * `@cloudflare/voice/react`).
 *
 * Two copies = two dispatchers, and the second `useMemo` call hits a
 * dispatcher that's `null` for that React's current render tree:
 *
 *   "TypeError: Cannot read properties of null (reading 'useMemo')"
 *
 * To prevent this, we pin `react` / `react-dom` / `react/jsx-runtime`
 * (and their `/client` subpaths) to the project root's copy via a Bun
 * plugin. The user installs React once in their app; every package in
 * the bundle uses that single resolved path.
 */
export async function bundleApp(params: {
  appEntry: string;
  projectRoot: string;
}): Promise<string> {
  const result = await Bun.build({
    entrypoints: [params.appEntry],
    target: "browser",
    format: "esm",
    minify: true,
    root: params.projectRoot,
    plugins: [reactDedupePlugin(params.projectRoot)],
  });

  if (!result.success || result.outputs.length === 0) {
    const messages = result.logs.map((l) => String(l)).join("\n");
    throw new Error(
      `failed to bundle ${params.appEntry}\n${messages || "(no log messages)"}`,
    );
  }

  // The outputs array contains the entry chunk plus any split chunks. For
  // our minimal setup (single entry, no dynamic imports in app.tsx), the
  // first output is the bundled entry.
  return await result.outputs[0]!.text();
}

/**
 * Bun plugin that pins every `react` / `react-dom` import (and the
 * common subpaths) to the project root's resolved location.
 *
 * Without this, a symlinked framework can bring a second React copy
 * into the bundle via its own `node_modules`, and the React
 * "no active dispatcher" error fires on the first hook call from
 * the wrong copy.
 *
 * Implementation notes:
 *   - We resolve each module once eagerly (sync) at plugin construction
 *     time and cache the result. Bun's `onResolve` callback runs per
 *     import; using a cached canonical path keeps the hot path trivial.
 *   - If the resolver throws (no React installed in the project — fine
 *     for non-React agents), we leave the import untouched and let
 *     Bun's default resolver run. That way bundling a non-React
 *     example doesn't fail just because of a missing peer.
 */
function reactDedupePlugin(projectRoot: string): import("bun").BunPlugin {
  const SUBPATHS = [
    "react",
    "react/jsx-runtime",
    "react/jsx-dev-runtime",
    "react-dom",
    "react-dom/client",
  ];

  // Resolve each subpath from the project root once. Bun.resolveSync
  // walks up parent dirs the same way module resolution does at
  // runtime, so this gives us the canonical absolute path.
  const canonical = new Map<string, string>();
  for (const spec of SUBPATHS) {
    try {
      canonical.set(spec, Bun.resolveSync(spec, projectRoot));
    } catch {
      // No React installed in the project (e.g. an agent without
      // a UI); leave this entry off the map.
    }
  }

  return {
    name: "ayjnt:react-dedupe",
    setup(build) {
      // One filter per pinned import path. Bun's onResolve matches by
      // regex against the importer's specifier; we use exact-string
      // alternation so we don't accidentally rewrite e.g. `react-foo`.
      // The `^...$` anchors are essential.
      const pattern = new RegExp(
        `^(${SUBPATHS.map((s) => s.replace(/[/.]/g, "\\$&")).join("|")})$`,
      );
      build.onResolve({ filter: pattern }, (args) => {
        const target = canonical.get(args.path);
        if (!target) return null; // pass through to Bun's default
        return { path: target };
      });
    },
  };
}

function toImportSpec(fromDir: string, toFile: string): string {
  const rel = path.relative(fromDir, path.resolve(toFile)).replace(/\\/g, "/");
  return rel.startsWith(".") ? rel : "./" + rel;
}

/**
 * Heuristic check for a top-level ES `export default`.
 *
 * Recognizes:
 *   export default function X() {}
 *   export default class X {}
 *   export default async function X() {}
 *   export default X
 *   export default (expression)
 *   export { X as default }
 *   export { X as default, Y }  — any position inside the re-export list
 *
 * Limitation: this is a regex, not an AST walk. It can be fooled by
 * `export default` inside a template literal or a string, and it
 * ignores block comments. For the file shapes we care about (agent
 * app.tsx files that either end with the legacy `createRoot` call or
 * start with `export default function X`) the precision is enough. If
 * a future need arises — detecting default exports inside generated or
 * obfuscated code — swap this for a Bun.Transpiler-backed scan.
 */
export function hasDefaultExport(source: string): boolean {
  // Drop line comments so `// export default commented` doesn't match.
  const withoutLineComments = source.replace(/^\s*\/\/.*$/gm, "");
  // `export default ...` at the start of a line.
  if (/^\s*export\s+default\b/m.test(withoutLineComments)) return true;
  // `export { X as default }` — the default may appear anywhere in the
  // brace group.
  if (/^\s*export\s*\{[^}]*\bas\s+default\b[^}]*\}/m.test(withoutLineComments)) {
    return true;
  }
  return false;
}

/**
 * Generate the `.ayjnt/client/<route>/mount.tsx` wrapper that the
 * framework bundles in place of the user's `app.tsx` when the user
 * follows the `export default` convention.
 *
 * The wrapper:
 *   - Boots React in StrictMode.
 *   - Catches render errors in a minimal ErrorBoundary so the dev
 *     overlay is a readable stack, not a blank page.
 *   - Targets `#root` — same contract as {@link generateHtmlShell}.
 *
 * @param params.appImportPath  Import specifier (relative from the
 *   mount file) to the user's `app.tsx`, e.g. `"../../../agents/counter/app.tsx"`.
 */
export function generateMountEntry(params: {
  appImportPath: string;
}): string {
  return `// GENERATED by ayjnt — do not edit.
// Bundled in place of the user's app.tsx when it exports a default
// React component. The user writes the component, we handle the mount.
import { StrictMode, Component, type ReactNode } from "react";
import { createRoot } from "react-dom/client";
import App from "${params.appImportPath}";

class AyjntErrorBoundary extends Component<
  { children: ReactNode },
  { error: unknown }
> {
  state: { error: unknown } = { error: null };
  static getDerivedStateFromError(error: unknown) {
    return { error };
  }
  componentDidCatch(error: unknown) {
    // eslint-disable-next-line no-console
    console.error("[ayjnt] render error:", error);
  }
  render() {
    if (this.state.error) {
      const e = this.state.error as Error;
      return (
        <pre
          style={{
            margin: 0,
            padding: 16,
            background: "#fff3f3",
            color: "#900",
            fontFamily: "ui-monospace, SFMono-Regular, monospace",
            fontSize: 12,
            lineHeight: 1.4,
            whiteSpace: "pre-wrap",
          }}
        >
          {String(e?.stack ?? e)}
        </pre>
      );
    }
    return this.props.children;
  }
}

const el = document.getElementById("root");
if (!el) throw new Error("[ayjnt] mount target #root missing");
createRoot(el).render(
  <StrictMode>
    <AyjntErrorBoundary>
      <App />
    </AyjntErrorBoundary>
  </StrictMode>,
);
`;
}
