// Client-side code generation — tsconfig for path aliases, env.d.ts for the
// generated Env type, and one typed useAgent hook per agent.
//
// Files land in <root>/.ayjnt/ alongside migrations.json and dist/. The
// user gitignores .ayjnt/* except migrations.json. To pick up the path
// aliases, their own tsconfig.json needs to:
//
//   {
//     "extends": "./.ayjnt/tsconfig.json",
//     ...
//   }
//
// After that, `import { useAgent } from "@ayjnt/chat"` resolves to
// .ayjnt/client/chat/index.tsx, and `import type { GeneratedEnv } from
// "@ayjnt/env"` resolves to .ayjnt/env.d.ts.

import * as path from "node:path";
import type { AgentEntry, Manifest } from "../core/types.ts";

/**
 * tsconfig.json the user extends to get path aliases for generated code.
 *
 * Paths are resolved relative to the file that defines them (TS behavior),
 * so `./client/*` here means .ayjnt/client/* — works regardless of where
 * the extending tsconfig lives in the project tree.
 */
export function generateTsconfig(): string {
  const config = {
    compilerOptions: {
      paths: {
        "@ayjnt/env": ["./env.d.ts"],
        "@ayjnt/*": ["./client/*"],
      },
    },
  };
  const header =
    "// GENERATED by ayjnt — do not edit. Extended by your tsconfig.json.\n";
  return header + JSON.stringify(config, null, 2) + "\n";
}

/**
 * Declares the GeneratedEnv type with every agent's DO binding. Extend it
 * with your own KV/R2/etc bindings:
 *
 *   import type { GeneratedEnv } from "@ayjnt/env";
 *   type Env = GeneratedEnv & { KV: KVNamespace };
 *
 * @param manifest  scan result
 * @param outPath   absolute path to the env.d.ts we're emitting (used for
 *                  computing relative imports to agent source files)
 */
export function generateEnvTypes(
  manifest: Manifest,
  outPath: string,
): string {
  const outDir = path.dirname(path.resolve(outPath));

  const imports = manifest.agents
    .map((a) => {
      const rel = toImportSpec(outDir, a.sourceFile);
      return `import type ${a.className} from "${rel}";`;
    })
    .join("\n");

  const fields = manifest.agents
    .map(
      (a) =>
        `  ${a.binding}: DurableObjectNamespace<${a.className}>;`,
    )
    .join("\n");

  return `// GENERATED by ayjnt — do not edit.
${imports || "// (no agents discovered)"}

/**
 * Every Durable Object binding derived from the file tree under agents/.
 * Extend this with your own wrangler bindings (KV, R2, vars):
 *
 *   import type { GeneratedEnv } from "@ayjnt/env";
 *   type Env = GeneratedEnv & { KV: KVNamespace };
 */
export type GeneratedEnv = {
${fields || "  // no agents"}
};
`;
}

/**
 * Typed useAgent hook for one agent. The user imports:
 *
 *   import { useAgent } from "@ayjnt/<route>";
 *
 * The hook pre-fills `basePath` from the agent's route prefix + an
 * instance name derived from the current URL (first path segment after
 * the prefix). Override with `useAgent({ name: "custom-id" })`.
 *
 * @param agent     one entry from the manifest
 * @param outPath   absolute path to the client/<route>/index.tsx we're
 *                  emitting (used for the relative import to agent.ts)
 */
export function generateClientHook(
  agent: AgentEntry,
  outPath: string,
): string {
  const outDir = path.dirname(path.resolve(outPath));
  const agentImport = toImportSpec(outDir, agent.sourceFile);
  const routePath = agent.routePath;
  const className = agent.className;

  return `// GENERATED by ayjnt — do not edit.
// Typed useAgent hook for ${className} at ${routePath}.
import {
  useAgent as useAgentUpstream,
  type UseAgentOptions,
} from "agents/react";
import type ${className} from "${agentImport}";

/** The agent class, re-exported so callers can \`import type { ${className} } from "@ayjnt/...".\` */
export type { default as ${className} } from "${agentImport}";

type Instance = InstanceType<typeof ${className}>;
type DefaultState = Instance extends { state: infer S } ? S : unknown;

/**
 * React hook bound to ${className}. Derives \`basePath\` from the agent's
 * route prefix "${routePath}" and an instance name taken from the current
 * URL. Pass \`name\` to override the instance:
 *
 *   const agent = useAgent();                       // URL-derived
 *   const agent = useAgent({ name: "room-42" });    // explicit
 *   const agent = useAgent<MyState>();              // custom State type
 */
export function useAgent<State = DefaultState>(
  options?: Omit<UseAgentOptions<State>, "agent" | "basePath"> & {
    /** Override the URL-derived instance name. */
    name?: string;
  },
): ReturnType<typeof useAgentUpstream<State>> {
  const { name: overrideName, ...rest } = options ?? {};
  const instanceName = overrideName ?? deriveInstance();
  return useAgentUpstream<State>({
    agent: ${JSON.stringify(className)},
    basePath: ${JSON.stringify(routePath.slice(1))} + "/" + instanceName,
    ...rest,
  });
}

/**
 * Pull the instance name out of window.location.pathname.
 *
 *   /${routePath.slice(1)}                        → "default"
 *   /${routePath.slice(1)}/room-42                → "room-42"
 *   /${routePath.slice(1)}/room-42/anything-else  → "room-42"
 */
function deriveInstance(): string {
  if (typeof window === "undefined") return "default";
  const prefix = ${JSON.stringify(routePath)};
  const p = window.location.pathname;
  if (p !== prefix && !p.startsWith(prefix + "/")) return "default";
  const remainder = p.slice(prefix.length);
  const parts = remainder.split("/").filter(Boolean);
  return parts[0] ?? "default";
}
`;
}

/**
 * Path in .ayjnt/client where a given agent's hook belongs. Uses routePath
 * (not folderPath) because route groups are stripped from URLs and should
 * be stripped from the import alias too.
 *
 *   routePath "/chat"        → "client/chat/index.tsx"
 *   routePath "/admin/users" → "client/admin/users/index.tsx"
 */
export function clientFileFor(agent: AgentEntry): string {
  const segments = agent.routePath.slice(1).split("/").filter(Boolean);
  return path.join("client", ...segments, "index.tsx");
}

/**
 * HTML shell for an agent with a co-located app.tsx. References the bundled
 * JS via a `<script src>` pointing at the Cloudflare Assets binding path
 * — we DO NOT inline the JS. Inlining broke because minified bundles
 * reliably contain `</script>` substrings (in regex literals and string
 * contents), which terminate the script tag mid-parse and dump the rest
 * as raw HTML text. Serving the bundle as a standalone asset avoids the
 * escaping problem entirely and lets Cloudflare's CDN cache it.
 */
export function generateHtmlShell(params: {
  title: string;
  /** Absolute URL path (relative to origin) where the app.js bundle lives.
   *  E.g. "/__ayjnt/counter/app.js". */
  scriptSrc: string;
}): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${escapeHtml(params.title)}</title>
</head>
<body>
<div id="root"></div>
<script type="module" src="${escapeHtml(params.scriptSrc)}"></script>
</body>
</html>
`;
}

/**
 * Flatten a route path into a filename-safe segment for the assets tree.
 *
 *   "/chat"        → "chat"
 *   "/admin/users" → "admin_users"
 *
 * Used to pick the subdirectory under .ayjnt/assets/__ayjnt/ where an
 * agent's bundled JS and HTML live, and to construct the public URL path
 * the HTML shell references.
 */
export function flattenRoute(routePath: string): string {
  return routePath.slice(1).replace(/\//g, "_");
}

function escapeHtml(s: string): string {
  return s.replace(/[&<>"']/g, (c) => ({
    "&": "&amp;",
    "<": "&lt;",
    ">": "&gt;",
    '"': "&quot;",
    "'": "&#39;",
  })[c] ?? c);
}

/**
 * Bundle an agent's app.tsx into a single browser-targeted ES module
 * string, ready to inline into a <script type="module"> tag.
 *
 * Uses Bun.build with target: "browser" so React, agents/react, and the
 * generated typed hook all get pulled in and tree-shaken. Minified to keep
 * worker bundle size down.
 */
export async function bundleApp(params: {
  appEntry: string;
  projectRoot: string;
}): Promise<string> {
  const result = await Bun.build({
    entrypoints: [params.appEntry],
    target: "browser",
    format: "esm",
    minify: true,
    root: params.projectRoot,
  });

  if (!result.success || result.outputs.length === 0) {
    const messages = result.logs.map((l) => String(l)).join("\n");
    throw new Error(
      `failed to bundle ${params.appEntry}\n${messages || "(no log messages)"}`,
    );
  }

  // The outputs array contains the entry chunk plus any split chunks. For
  // our minimal setup (single entry, no dynamic imports in app.tsx), the
  // first output is the bundled entry.
  return await result.outputs[0]!.text();
}

function toImportSpec(fromDir: string, toFile: string): string {
  const rel = path.relative(fromDir, path.resolve(toFile)).replace(/\\/g, "/");
  return rel.startsWith(".") ? rel : "./" + rel;
}
