// Worker entrypoint generator. Emits .ayjnt/dist/entry.ts — the actual worker
// the user's runtime runs on. We bypass routeAgentRequest and own the dispatch
// so URL shape stays under our control and nested routing / route groups work.
//
// Generated file:
//   - re-exports every agent class (required so DO can register them by name)
//   - builds a route table sorted longest-prefix first
//   - exports a default { fetch } that matches the route, forwards to the DO
//
// Why getAgentByName and not raw idFromName + get:
//   The Agent base class emits a CF_AGENT_IDENTITY WebSocket message on
//   connect with { name: this.name, agent: kebab(ClassName) }. The client
//   (useAgent / AgentClient / agentFetch) uses this to know which instance
//   it's talking to. The DO only learns its `name` when the server calls
//   `stub.setName(name)` — which is what getAgentByName does under the
//   hood. Skipping it means the DO has no `this.name`, and every identity
//   message to the client is wrong. See docs/README for client details.

import * as path from "node:path";
import type { Manifest } from "../core/types.ts";

export type EntryOptions = {
  /** Absolute path where the generated entry.ts will be written. Used to
   *  compute relative imports of agent sources. */
  outPath: string;
};

export function generateEntry(
  manifest: Manifest,
  options: EntryOptions,
): string {
  const outDir = path.dirname(path.resolve(options.outPath));
  const agents = manifest.agents;

  // Sort routes longest-first so prefix matching picks the specific route.
  // /admin/users must beat /admin if both existed.
  const routes = [...agents].sort(
    (a, b) => b.routePath.length - a.routePath.length,
  );

  const imports = agents
    .map((a) => {
      const rel = toImportSpec(outDir, a.sourceFile);
      return `export { default as ${a.className} } from "${rel}";`;
    })
    .join("\n");

  const routeEntries = routes
    .map(
      (a) =>
        `  { prefix: ${JSON.stringify(a.routePath)}, binding: ${JSON.stringify(a.binding)} },`,
    )
    .join("\n");

  const bindingUnion =
    agents.length === 0
      ? "never"
      : agents.map((a) => JSON.stringify(a.binding)).join(" | ");

  return `// GENERATED by ayjnt — do not edit. Regenerated on every build.
import { getAgentByName } from "agents";
${imports || "// (no agents discovered)"}

type Binding = ${bindingUnion};

type Env = Record<Binding, DurableObjectNamespace>;

const ROUTES: ReadonlyArray<{ prefix: string; binding: Binding }> = [
${routeEntries}
];

function matchRoute(pathname: string): {
  binding: Binding;
  instanceId: string;
  rest: string;
} | null {
  for (const route of ROUTES) {
    if (
      pathname === route.prefix ||
      pathname.startsWith(route.prefix + "/")
    ) {
      const remainder = pathname.slice(route.prefix.length);
      const parts = remainder.split("/").filter(Boolean);
      const instanceId = parts[0];
      if (!instanceId) return null;
      const rest = "/" + parts.slice(1).join("/");
      return { binding: route.binding, instanceId, rest };
    }
  }
  return null;
}

export default {
  async fetch(
    request: Request,
    env: Env,
    _ctx: ExecutionContext,
  ): Promise<Response> {
    const url = new URL(request.url);
    const match = matchRoute(url.pathname);
    if (!match) {
      return new Response("Not found", { status: 404 });
    }
    // getAgentByName does: idFromName → get → stub.setName(name). The
    // setName step is what teaches the DO its own identity so the
    // CF_AGENT_IDENTITY message to the client is correct.
    const stub = await getAgentByName(env[match.binding], match.instanceId);
    const forwarded = new URL(url);
    forwarded.pathname = match.rest || "/";
    return stub.fetch(new Request(forwarded, request));
  },
};
`;
}

/**
 * Build a module specifier for `import { ... } from "<spec>"` pointing from
 * the generated entry file to an agent source file. Always produces a
 * forward-slash path starting with "./" or "../".
 */
function toImportSpec(fromDir: string, toFile: string): string {
  const rel = path.relative(fromDir, path.resolve(toFile)).replace(/\\/g, "/");
  return rel.startsWith(".") ? rel : "./" + rel;
}
