// Worker entrypoint generator. Emits .ayjnt/dist/entry.ts — the actual worker
// the user's runtime runs on. We bypass routeAgentRequest and own the dispatch
// so URL shape stays under our control and nested routing / route groups work.
//
// Generated file:
//   - re-exports every agent class (required so DO can register them by name)
//   - imports every unique middleware.ts file once
//   - builds a route table sorted longest-prefix first, with each route
//     carrying its own ordered middleware chain (root → leaf)
//   - exports a default { fetch } that matches the route, runs the chain
//     via `compose`, then forwards to the DO via `getAgentByName`
//
// Why getAgentByName and not raw idFromName + get:
//   The Agent base class emits a CF_AGENT_IDENTITY WebSocket message on
//   connect with { name: this.name, agent: kebab(ClassName) }. The client
//   (useAgent / AgentClient / agentFetch) uses this to know which instance
//   it's talking to. The DO only learns its `name` when the server calls
//   `stub.setName(name)` — which is what getAgentByName does under the
//   hood. Skipping it means the DO has no `this.name`, and every identity
//   message to the client is wrong. See docs/README for client details.

import * as path from "node:path";
import type { Manifest } from "../core/types.ts";

export type EntryOptions = {
  /** Absolute path where the generated entry.ts will be written. Used to
   *  compute relative imports of agent sources and middleware. */
  outPath: string;
};

export function generateEntry(
  manifest: Manifest,
  options: EntryOptions,
): string {
  const outDir = path.dirname(path.resolve(options.outPath));
  const agents = manifest.agents;

  // Collect unique middleware files across all agents, preserving first-seen
  // order. Each gets a stable `mw_<N>` import name.
  const middlewareIndex = new Map<string, number>();
  for (const a of agents) {
    for (const mw of a.middlewareChain) {
      if (!middlewareIndex.has(mw)) middlewareIndex.set(mw, middlewareIndex.size);
    }
  }

  // Sort routes longest-first so prefix matching picks the specific route.
  // /admin/users must beat /admin if both existed.
  const routes = [...agents].sort(
    (a, b) => b.routePath.length - a.routePath.length,
  );

  const agentImports = agents
    .map((a) => {
      const rel = toImportSpec(outDir, a.sourceFile);
      return `export { default as ${a.className} } from "${rel}";`;
    })
    .join("\n");

  const middlewareImports = [...middlewareIndex.entries()]
    .map(([file, i]) => `import mw_${i} from "${toImportSpec(outDir, file)}";`)
    .join("\n");

  const routeEntries = routes
    .map((a) => {
      const chain = a.middlewareChain
        .map((f) => `mw_${middlewareIndex.get(f)!}`)
        .join(", ");
      return `  { prefix: ${JSON.stringify(a.routePath)}, binding: ${JSON.stringify(a.binding)}, middleware: [${chain}] },`;
    })
    .join("\n");

  const bindingUnion =
    agents.length === 0
      ? "never"
      : agents.map((a) => JSON.stringify(a.binding)).join(" | ");

  return `// GENERATED by ayjnt — do not edit. Regenerated on every build.
import { getAgentByName } from "agents";
import { compose, createContext, type Middleware } from "ayjnt/middleware";
${middlewareImports}
${agentImports || "// (no agents discovered)"}

type Binding = ${bindingUnion};

type Env = Record<Binding, DurableObjectNamespace>;

type Route = {
  prefix: string;
  binding: Binding;
  middleware: Middleware<any>[];
};

const ROUTES: Route[] = [
${routeEntries}
];

type Match = {
  binding: Binding;
  instanceId: string;
  rest: string;
  middleware: Middleware<any>[];
};

function matchRoute(pathname: string): Match | null {
  for (const route of ROUTES) {
    if (
      pathname === route.prefix ||
      pathname.startsWith(route.prefix + "/")
    ) {
      const remainder = pathname.slice(route.prefix.length);
      const parts = remainder.split("/").filter(Boolean);
      const instanceId = parts[0];
      if (!instanceId) return null;
      const rest = "/" + parts.slice(1).join("/");
      return {
        binding: route.binding,
        instanceId,
        rest,
        middleware: route.middleware,
      };
    }
  }
  return null;
}

export default {
  async fetch(
    request: Request,
    env: Env,
    executionCtx: ExecutionContext,
  ): Promise<Response> {
    const url = new URL(request.url);
    const match = matchRoute(url.pathname);
    if (!match) {
      return new Response("Not found", { status: 404 });
    }

    // getAgentByName does: idFromName → get → stub.setName(name). The
    // setName step is what teaches the DO its own identity so the
    // CF_AGENT_IDENTITY message to the client is correct.
    const finalize = async (): Promise<Response> => {
      const stub = await getAgentByName(env[match.binding], match.instanceId);
      const forwarded = new URL(url);
      forwarded.pathname = match.rest || "/";
      return stub.fetch(new Request(forwarded, request));
    };

    if (match.middleware.length === 0) return finalize();

    const c = createContext({
      request,
      url,
      env,
      executionCtx,
      params: { instanceId: match.instanceId, pathSuffix: match.rest },
    });
    return compose(match.middleware, c, finalize);
  },
};
`;
}

/**
 * Build a module specifier for `import { ... } from "<spec>"` pointing from
 * the generated entry file to a source file. Always produces a forward-slash
 * path starting with "./" or "../".
 */
function toImportSpec(fromDir: string, toFile: string): string {
  const rel = path.relative(fromDir, path.resolve(toFile)).replace(/\\/g, "/");
  return rel.startsWith(".") ? rel : "./" + rel;
}
