// Root-level WebAssembly module convention.
//
// A project may place compiled artifacts under:
//
//   modules/math.wasm
//   modules/image/resize.wasm
//
// Build codegen mirrors each artifact with a tiny TypeScript proxy under
// `.ayjnt/client/modules/`, producing stable imports such as
// `@ayjnt/modules/math` and `@ayjnt/modules/image/resize`. The proxy exists
// solely for path stability and TypeScript's benefit; Wrangler still sees a
// normal static `.wasm` import and packages it as a CompiledWasm module.

import { Glob } from "bun";
import { existsSync } from "node:fs";
import * as path from "node:path";
import type { WasmModuleEntry } from "../core/types.ts";

const WASM_MAGIC = [0x00, 0x61, 0x73, 0x6d] as const;

/** Discover and minimally validate every compiled artifact under modules/. */
export async function scanWasmModules(root: string): Promise<WasmModuleEntry[]> {
  const modulesDir = path.join(root, "modules");
  if (!existsSync(modulesDir)) return [];

  const entries: WasmModuleEntry[] = [];
  const glob = new Glob("**/*.wasm");
  for await (const rawRel of glob.scan({ cwd: modulesDir, onlyFiles: true })) {
    const modulePath = rawRel.replace(/\\/g, "/");
    const sourceFile = path.join(modulesDir, rawRel);
    await assertWasmArtifact(sourceFile);
    entries.push({
      modulePath,
      importPath: `@ayjnt/modules/${modulePath.slice(0, -".wasm".length)}`,
      sourceFile,
    });
  }

  entries.sort((a, b) => a.modulePath.localeCompare(b.modulePath));
  assertPortablePaths(entries);
  return entries;
}

/** Path of the generated proxy relative to `.ayjnt/client/modules/`. */
export function wasmProxyPath(entry: WasmModuleEntry): string {
  return entry.modulePath.replace(/\.wasm$/, ".ts");
}

/** Generate one typed proxy around Wrangler's CompiledWasm default export. */
export function generateWasmProxy(
  entry: WasmModuleEntry,
  outPath: string,
): string {
  let rel = path.relative(path.dirname(outPath), entry.sourceFile).replace(/\\/g, "/");
  if (!rel.startsWith(".")) rel = `./${rel}`;

  return `// GENERATED by ayjnt — do not edit.\n` +
    `// Wrangler loads this artifact as a precompiled WebAssembly.Module.\n` +
    `// @ts-ignore TypeScript does not understand Wrangler's CompiledWasm modules.\n` +
    `import wasmModule from ${JSON.stringify(rel)};\n\n` +
    `export default wasmModule as WebAssembly.Module;\n`;
}

async function assertWasmArtifact(file: string): Promise<void> {
  const bytes = new Uint8Array(await Bun.file(file).slice(0, 4).arrayBuffer());
  if (
    bytes.length !== WASM_MAGIC.length ||
    WASM_MAGIC.some((value, index) => bytes[index] !== value)
  ) {
    throw new Error(
      `${file}: not a compiled WebAssembly module (missing the \\0asm header). ` +
        `Compile the source language to a .wasm artifact before running ayjnt.`,
    );
  }
}

/** Reject names that collapse on the case-insensitive filesystems supported
 *  by Ayjnt. Without this, two imports can work in CI but overwrite the same
 *  generated proxy on a developer machine. */
function assertPortablePaths(entries: WasmModuleEntry[]): void {
  const seen = new Map<string, string>();
  for (const entry of entries) {
    const key = entry.modulePath.toLocaleLowerCase("en-US");
    const prior = seen.get(key);
    if (prior) {
      throw new Error(
        `WebAssembly module paths differ only by case: "${prior}" and ` +
          `"${entry.modulePath}". Rename one so generated imports are portable.`,
      );
    }
    seen.set(key, entry.modulePath);
  }
}
