// Wrangler config generator. Emits the JSON that wrangler dev/deploy reads.
// Written to <root>/.ayjnt/dist/wrangler.jsonc. Users never touch it.
//
// Inputs:
//   - manifest: drives durable_objects.bindings (name from binding, class_name
//     from className)
//   - lockfile: drives migrations (verbatim). Callers pass the lockfile AFTER
//     applying any diff, so any pending migration is already baked in.
//   - options: project name (from package.json, sanitized), compatibility
//     date, optional user overrides.

import type { Manifest, MigrationLockfile } from "../core/types.ts";

export type WranglerOptions = {
  /** Worker name. Must match `^[a-z0-9_-]+$`. */
  name: string;
  /** Compatibility date (YYYY-MM-DD). Defaults to today. */
  compatibilityDate?: string;
  /** Additional compatibility flags. "nodejs_compat" is always included. */
  compatibilityFlags?: string[];
  /** User-supplied overrides merged into the output (e.g. routes, vars). */
  extras?: Record<string, unknown>;
  /** True when at least one agent has a co-located app.tsx. Triggers the
   *  `assets` config block so Cloudflare ships .ayjnt/assets/ as static
   *  files bound as `env.ASSETS`. */
  hasApps?: boolean;
};

/**
 * Generate a wrangler.jsonc string. The output is actually JSON with a
 * single leading comment — safe to write with a .jsonc extension and still
 * parse with JSON.parse after stripping the comment (which wrangler does).
 */
export function generateWrangler(
  manifest: Manifest,
  lockfile: MigrationLockfile,
  options: WranglerOptions,
): string {
  const {
    name,
    compatibilityDate = today(),
    compatibilityFlags = [],
    extras = {},
    hasApps = false,
  } = options;

  assertValidName(name);

  const flags = Array.from(
    new Set<string>(["nodejs_compat", ...compatibilityFlags]),
  );

  const config: Record<string, unknown> = {
    ...extras,
    $schema: "node_modules/wrangler/config-schema.json",
    name,
    main: "./entry.ts",
    compatibility_date: compatibilityDate,
    compatibility_flags: flags,
    durable_objects: {
      bindings: manifest.agents.map((a) => ({
        name: a.binding,
        class_name: a.className,
      })),
    },
    migrations: lockfile.migrations.map(stripUndefined),
  };

  // The assets config points wrangler at .ayjnt/assets/ (one level up from
  // wrangler.jsonc).
  //
  // - `not_found_handling: "none"` makes 404s fall through to the worker so
  //   agent requests reach the DO even though assets are served from the
  //   same origin.
  //
  // - `html_handling: "none"` is the critical bit: the default
  //   ("auto-trailing-slash") issues a 301 for "/__ayjnt/<flat>/index.html"
  //   → "/__ayjnt/<flat>/", which leaks into the browser URL bar. The
  //   worker's HTML dispatch does `env.ASSETS.fetch("/__ayjnt/<flat>/
  //   index.html")` and forwards the response; a redirect from ASSETS
  //   becomes a redirect the browser follows, so the user ends up at
  //   "/__ayjnt/<flat>/" instead of their intended "/<route>/<instanceId>"
  //   and the client-side useAgent hook can't derive the instance name
  //   from window.location.pathname. Setting it to "none" keeps the
  //   response as a plain 200 with the HTML body, the browser stays at
  //   the original URL, and the hook sees the right instance.
  if (hasApps) {
    config["assets"] = {
      directory: "../assets",
      binding: "ASSETS",
      not_found_handling: "none",
      html_handling: "none",
    };
  }

  const header =
    "// GENERATED by ayjnt — do not edit. Regenerated on every `ayjnt build`.\n";
  return header + JSON.stringify(config, null, 2) + "\n";
}

function today(): string {
  const d = new Date();
  const year = d.getUTCFullYear();
  const month = String(d.getUTCMonth() + 1).padStart(2, "0");
  const day = String(d.getUTCDate()).padStart(2, "0");
  return `${year}-${month}-${day}`;
}

function assertValidName(name: string): void {
  if (!/^[a-z0-9_-]+$/.test(name)) {
    throw new Error(
      `Invalid worker name "${name}". Wrangler requires lowercase letters, digits, hyphens, and underscores only.`,
    );
  }
}

/** Strip undefined fields from migration entries so JSON stays clean. */
function stripUndefined<T extends Record<string, unknown>>(obj: T): T {
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(obj)) {
    if (v !== undefined) out[k] = v;
  }
  return out as T;
}

/**
 * Derive a wrangler-valid name from a package.json "name" field.
 *   "@scope/package" → "package"
 *   "My Cool App"    → "my-cool-app"
 */
export function deriveWorkerName(packageName: string): string {
  const withoutScope = packageName.replace(/^@[^/]+\//, "");
  return withoutScope
    .toLowerCase()
    .replace(/[^a-z0-9_-]+/g, "-")
    .replace(/^-+|-+$/g, "");
}
