// GENERATED by ayjnt — do not edit.
// Bundled in place of the user's app.tsx when it exports a default
// React component. The user writes the component, we handle the mount.
import { StrictMode, Component, type ReactNode } from "react";
import { createRoot } from "react-dom/client";
import App from "../../../agents/room/app.tsx";

class AyjntErrorBoundary extends Component<
  { children: ReactNode },
  { error: unknown }
> {
  state: { error: unknown } = { error: null };
  static getDerivedStateFromError(error: unknown) {
    return { error };
  }
  componentDidCatch(error: unknown) {
    // eslint-disable-next-line no-console
    console.error("[ayjnt] render error:", error);
  }
  render() {
    if (this.state.error) {
      const e = this.state.error as Error;
      return (
        <pre
          style={{
            margin: 0,
            padding: 16,
            background: "#fff3f3",
            color: "#900",
            fontFamily: "ui-monospace, SFMono-Regular, monospace",
            fontSize: 12,
            lineHeight: 1.4,
            whiteSpace: "pre-wrap",
          }}
        >
          {String(e?.stack ?? e)}
        </pre>
      );
    }
    return this.props.children;
  }
}

const el = document.getElementById("root");
if (!el) throw new Error("[ayjnt] mount target #root missing");
createRoot(el).render(
  <StrictMode>
    <AyjntErrorBoundary>
      <App />
    </AyjntErrorBoundary>
  </StrictMode>,
);
