import { DocPageShell } from "@/components/DocPageShell";
import { Callout } from "@/components/Callout";
import { CodeBlock } from "@/components/CodeBlock";

export const metadata = {
	title: "Generated files — ayjnt docs",
	description:
		"Every file ayjnt emits, what it contains, whether it's committed, and when it's regenerated.",
};

export default function Page() {
	return (
		<DocPageShell
			slug="reference/generated-files"
			lede="Everything in .ayjnt/ is regenerated on every build. This page is the reference for what each file is, whether you should commit it, and what it's used for."
		>
			<h2>Commitment status</h2>
			<table>
				<thead>
					<tr>
						<th>File</th>
						<th>Commit?</th>
						<th>Why</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>
							<code>.ayjnt/migrations.json</code>
						</td>
						<td>
							<strong>Yes</strong>
						</td>
						<td>
							Source of truth for what DO schema is in production.
							Append-only history.
						</td>
					</tr>
					<tr>
						<td>
							<code>.ayjnt/tsconfig.json</code>
						</td>
						<td>No</td>
						<td>Regenerated each build. Path aliases.</td>
					</tr>
					<tr>
						<td>
							<code>.ayjnt/env.d.ts</code>
						</td>
						<td>No</td>
						<td>
							Regenerated each build. Types the DO bindings.
						</td>
					</tr>
					<tr>
						<td>
							<code>.ayjnt/client/*</code>
						</td>
						<td>No</td>
						<td>Regenerated per-agent hook modules.</td>
					</tr>
					<tr>
						<td>
							<code>.ayjnt/dist/entry.ts</code>
						</td>
						<td>No</td>
						<td>Worker entrypoint. Fed to wrangler.</td>
					</tr>
					<tr>
						<td>
							<code>.ayjnt/dist/wrangler.jsonc</code>
						</td>
						<td>No</td>
						<td>Generated wrangler config.</td>
					</tr>
					<tr>
						<td>
							<code>.ayjnt/assets/__ayjnt/*</code>
						</td>
						<td>No</td>
						<td>Bundled UI HTML + JS per agent with app.tsx.</td>
					</tr>
				</tbody>
			</table>
			<p>
				The <code>ayjnt new</code> template&apos;s <code>.gitignore</code>{" "}
				captures this with:
			</p>
			<CodeBlock
				lang="sh"
				code={`.ayjnt/*
!.ayjnt/migrations.json`}
			/>

			<h2>.ayjnt/migrations.json</h2>
			<p>
				Committed lockfile. Source of truth for what DO schema is in
				production. Rewritten by <code>ayjnt build</code>; never written by
				<code>ayjnt deploy</code>.
			</p>
			<CodeBlock
				lang="json"
				code={`{
  "version": 1,
  "migrations": [
    {
      "tag": "v1",
      "timestamp": "2026-04-14T00:00:00Z",
      "new_sqlite_classes": ["ChatAgent"]
    },
    {
      "tag": "v2",
      "timestamp": "2026-04-14T05:30:00Z",
      "renamed_classes": [{ "from": "ChatAgent", "to": "TalkAgent" }]
    }
  ],
  "classes": {
    "chat": {
      "agentId": "chat",
      "className": "TalkAgent",
      "firstTag": "v1"
    }
  }
}`}
			/>
			<ul>
				<li>
					<code>version</code> — schema version of this file. Must be{" "}
					<code>1</code>.
				</li>
				<li>
					<code>migrations</code> — append-only list, consumed by wrangler
					as the <code>migrations</code> array in{" "}
					<code>wrangler.jsonc</code>. Never edit past entries.
				</li>
				<li>
					<code>classes</code> — derived state: what each agent{" "}
					<em>currently</em> is after all migrations. Keyed by{" "}
					<code>agentId</code>, so renames are detected across builds.
				</li>
			</ul>

			<h2>.ayjnt/dist/entry.ts</h2>
			<p>
				The worker&apos;s actual entrypoint. Wrangler bundles this when
				you deploy. You never edit it directly, but reading it is a great
				way to understand what ayjnt does. Typical shape:
			</p>
			<CodeBlock
				lang="ts"
				code={`// GENERATED by ayjnt — do not edit. Regenerated on every build.
import { getAgentByName } from "agents";
import { compose, createContext, type Middleware } from "ayjnt/middleware";
import mw_0 from "../../agents/middleware.ts";
import ChatAgent from "../../agents/chat/agent.ts";
import OrdersAgent from "../../agents/orders/agent.ts";

export { ChatAgent, OrdersAgent };  // required for DO class registration

type Binding = "CHAT_AGENT" | "ORDERS_AGENT";
type Env = Record<Binding, DurableObjectNamespace> & { ASSETS: Fetcher };

const ROUTES: Route[] = [
  { prefix: "/orders", binding: "ORDERS_AGENT", middleware: [mw_0], isMcp: false, assetFlat: null },
  { prefix: "/chat",   binding: "CHAT_AGENT",   middleware: [mw_0], isMcp: false, assetFlat: "chat" },
];

const CLASSES: Record<Binding, any> = { CHAT_AGENT: ChatAgent, ORDERS_AGENT: OrdersAgent };
const APPS: Partial<Record<Binding, string>> = { /* flat route -> app info */ };

function matchRoute(pathname: string): Match | null { /* longest-prefix match */ }
function isHtmlRequest(request: Request): boolean { /* GET + Accept: text/html + no Upgrade */ }

export default {
  async fetch(request, env, executionCtx) {
    const match = matchRoute(new URL(request.url).pathname);
    if (!match) return new Response("Not found", { status: 404 });

    const finalize = async () => {
      if (match.isMcp) return /* McpAgent.serve dispatch */;
      if (match.assetFlat && isHtmlRequest(request)) return /* HTML from Assets */;
      const stub = await getAgentByName(env[match.binding], match.instanceId);
      return stub.fetch(new Request(/* rewritten URL */, request));
    };

    if (!match.middleware.length) return finalize();
    const c = createContext({ /* ... */ });
    return compose(match.middleware, c, finalize);
  },
};`}
			/>
			<p>Key invariants:</p>
			<ul>
				<li>
					Every agent class is explicitly <code>export</code>ed so wrangler
					can find it for DO registration.
				</li>
				<li>Routes are sorted longest-prefix first.</li>
				<li>
					DO dispatch goes through <code>getAgentByName</code> to ensure
					<code>setName</code> is called (see{" "}
					<a
						href="/docs/guides/client-integration#why-the-server-uses-getagentbyname"
						className="link-underline"
					>
						Client integration
					</a>
					).
				</li>
				<li>
					MCP agents get special dispatch via their static{" "}
					<code>.serve()</code> method.
				</li>
			</ul>

			<h2>.ayjnt/dist/wrangler.jsonc</h2>
			<CodeBlock
				lang="jsonc"
				code={`// GENERATED by ayjnt — do not edit. Regenerated on every \`ayjnt build\`.
{
  "$schema": "node_modules/wrangler/config-schema.json",
  "name": "my-app",
  "main": "./entry.ts",
  "compatibility_date": "2026-04-14",
  "compatibility_flags": ["nodejs_compat"],
  "durable_objects": {
    "bindings": [
      { "name": "CHAT_AGENT",   "class_name": "ChatAgent" },
      { "name": "ORDERS_AGENT", "class_name": "OrdersAgent" }
    ]
  },
  "migrations": [
    { "tag": "v1", "new_sqlite_classes": ["ChatAgent", "OrdersAgent"] }
  ],
  "assets": {                              // only if any agent has app.tsx
    "directory": "../assets",
    "binding": "ASSETS",
    "not_found_handling": "none",
    "html_handling": "none"
  }
}`}
			/>
			<p>Fields set by ayjnt:</p>
			<ul>
				<li><code>name</code> — derived from your package.json.</li>
				<li><code>main</code> — always <code>./entry.ts</code>, relative to this wrangler config.</li>
				<li><code>compatibility_date</code> — today&apos;s date by default.</li>
				<li><code>compatibility_flags</code> — <code>nodejs_compat</code> is always included.</li>
				<li><code>durable_objects.bindings</code> — one per agent in the manifest.</li>
				<li><code>migrations</code> — copied verbatim from <code>.ayjnt/migrations.json</code>.</li>
				<li><code>assets</code> — only present if at least one agent has a co-located <code>app.tsx</code>. The <code>html_handling: &quot;none&quot;</code> setting is load-bearing (see <a href="/docs/guides/co-located-ui" className="link-underline">Co-located UI</a>).</li>
			</ul>

			<h2>.ayjnt/tsconfig.json</h2>
			<CodeBlock
				lang="jsonc"
				code={`// GENERATED by ayjnt — do not edit. Extended by your tsconfig.json.
{
  "compilerOptions": {
    "paths": {
      "@ayjnt/env": ["./env.d.ts"],
      "@ayjnt/*": ["./client/*"]
    }
  }
}`}
			/>
			<p>
				Your own <code>tsconfig.json</code> either{" "}
				<code>&quot;extends&quot;: &quot;./.ayjnt/tsconfig.json&quot;</code>{" "}
				(and you get the paths for free) or inlines the same mappings with
				<code>./</code> prefixes.
			</p>

			<h2>.ayjnt/env.d.ts</h2>
			<CodeBlock
				lang="ts"
				code={`// GENERATED by ayjnt — do not edit.
import type ChatAgent from "../agents/chat/agent.ts";
import type OrdersAgent from "../agents/orders/agent.ts";

export type GeneratedEnv = {
  CHAT_AGENT: DurableObjectNamespace<ChatAgent>;
  ORDERS_AGENT: DurableObjectNamespace<OrdersAgent>;
};`}
			/>

			<h2>.ayjnt/client/&lt;route&gt;/index.tsx</h2>
			<p>
				One file per agent — even agents without an <code>app.tsx</code>{" "}
				get one, since it&apos;s useful to import the typed hook from
				external apps too. Shape (for <code>agents/counter/</code>):
			</p>
			<CodeBlock
				lang="tsx"
				code={`// GENERATED by ayjnt — do not edit.
// Typed useAgent hook for CounterAgent at /counter.
import {
  useAgent as useAgentUpstream,
  type UseAgentOptions,
} from "agents/react";
import type CounterAgent from "../../../agents/counter/agent.ts";

export type { default as CounterAgent } from "../../../agents/counter/agent.ts";

type Instance = InstanceType<typeof CounterAgent>;
type DefaultState = Instance extends { state: infer S } ? S : unknown;

export function useAgent<State = DefaultState>(
  options?: Omit<UseAgentOptions<State>, "agent" | "basePath"> & {
    name?: string;
  },
): ReturnType<typeof useAgentUpstream<State>> {
  const { name: overrideName, ...rest } = options ?? {};
  const instanceName = overrideName ?? deriveInstance();
  return useAgentUpstream<State>({
    agent: "CounterAgent",
    basePath: "counter/" + instanceName,
    ...rest,
  });
}

function deriveInstance(): string {
  if (typeof window === "undefined") return "default";
  const prefix = "/counter";
  const p = window.location.pathname;
  if (p !== prefix && !p.startsWith(prefix + "/")) return "default";
  const remainder = p.slice(prefix.length);
  const parts = remainder.split("/").filter(Boolean);
  return parts[0] ?? "default";
}`}
			/>

			<h2>.ayjnt/assets/__ayjnt/&lt;route&gt;/</h2>
			<p>
				Only exists when an agent has a co-located <code>app.tsx</code>.
				Per-agent bundle directory. Example for <code>agents/counter/</code>:
			</p>
			<CodeBlock
				lang="sh"
				code={`.ayjnt/assets/__ayjnt/counter/
├── index.html              # HTML shell referencing app.js
└── app.js                  # Bun-built browser bundle of app.tsx`}
			/>
			<p>
				Cloudflare Assets binding serves these files. The{" "}
				<code>__ayjnt</code> prefix keeps them out of your route namespace
				— you can never create an agent at <code>/__ayjnt/&lt;anything&gt;</code>.
			</p>

			<h2>Regeneration cost</h2>
			<p>
				<code>ayjnt build</code> runs in ~30ms for typical projects
				(scan + lockfile diff + codegen). The slowest part is always{" "}
				<code>Bun.build</code> for <code>app.tsx</code> bundles — that
				scales with the size of your dependencies. React + Agents SDK adds
				about 150–450ms per agent with UI, so five UIs is a ~1.5 second
				rebuild.
			</p>
			<p>
				If you need faster incremental rebuilds, file an issue — sharing
				the bundle across agents is on the roadmap.
			</p>

			<Callout kind="tip" title="Safe to wipe">
				<p>
					If you suspect stale generation (after rebases, branch switches,
					debugging weird cache issues), <code>rm -rf .ayjnt/dist
					.ayjnt/client .ayjnt/tsconfig.json .ayjnt/env.d.ts .ayjnt/assets</code>{" "}
					is always safe. Only <code>.ayjnt/migrations.json</code> must
					stay put — don&apos;t delete it.
				</p>
			</Callout>
		</DocPageShell>
	);
}
