// GENERATED by ayjnt — do not edit.
import type SupportAgent from "../agents/support/agent.ts";

/**
 * Every Durable Object binding derived from the file tree under agents/,
 * plus any feature-flag-derived bindings (BROWSER, LOADER, AI, etc.) the
 * codegen added because of imports it detected.
 *
 * Extend this with your own wrangler bindings (KV, R2, vars):
 *
 *   import type { GeneratedEnv } from "@ayjnt/env";
 *   type Env = GeneratedEnv & { KV: KVNamespace };
 */
export type GeneratedEnv = {
  SUPPORT_AGENT: DurableObjectNamespace<SupportAgent>;
  /** Email send binding. Added when any agent implements onEmail(email). Used by this.sendEmail()/this.replyToEmail(). */
  EMAIL: SendEmail;
};
