// GENERATED by ayjnt — do not edit.
import type __AyjntAgent0 from "../agents/monitor/agent.ts";

/**
 * Project types merged into Ayjnt's runtime API. This is why agent authors can
 * write Agent<State> and this.workflow(params) without manually threading
 * GeneratedEnv or workflow bindings.
 */
declare global {
  namespace Ayjnt {
    interface GeneratedEnv {
    MONITOR_AGENT: DurableObjectNamespace<__AyjntAgent0>;
    }

    interface WorkflowRegistry {
      // no co-located workflows
    }
  }
}

/** Compatibility export for upstream Agent<Env, State> and custom env types. */
export type GeneratedEnv = Ayjnt.GeneratedEnv;
